linkWorkspacePackages: true
packages:
  - apps/*
  - packages/*
  - plugins
allowBuilds:
  '@google/genai': false
  canvas: false
  esbuild: true
  protobufjs: false
minimumReleaseAgeExclude:
  - quassel
patchedDependencies:
  quassel@0.4.5: patches/quassel@0.4.5.patch
