import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import ts from "typescript";
import type { ChannelContract, OperationContract } from "../../packages/ragents/src/rpc/contract";
import { canonicalHash } from "../../packages/ragents/src/runtime/canonical-hash";
import { canonicalJson } from "../../packages/ragents/src/runtime/canonical-json";
import { EXTENSION_API_VERSION } from "../../apps/server/src/extension-api";
import { extensionApi } from "./extension-api";

/** The fingerprint of the contract between VS Code extension and server, relative to the repository root; generated by pnpm update:extension-api. */
export const EXTENSION_API_RECORD_FILE = "apps/vscode/extension-api.json";

/** A SHA-256 per listed contract and file and the number they belong to. */
export interface ExtensionApiRecord {
  readonly version: number;
  readonly contracts: Readonly<Record<string, string>>;
  readonly files: Readonly<Record<string, string>>;
}

/** The structure of a type as JSON carries it: properties, elements, members, and literals; names and comments do not count. */
type Shape = string | { readonly [key: string]: Shape | readonly Shape[] };

const SCALAR = ts.TypeFlags.Any | ts.TypeFlags.Unknown | ts.TypeFlags.String | ts.TypeFlags.Number | ts.TypeFlags.Boolean
  | ts.TypeFlags.BigInt | ts.TypeFlags.Null | ts.TypeFlags.Undefined | ts.TypeFlags.Void | ts.TypeFlags.Never | ts.TypeFlags.ESSymbolLike
  | ts.TypeFlags.NonPrimitive | ts.TypeFlags.Literal | ts.TypeFlags.TemplateLiteral | ts.TypeFlags.EnumLike;

const byCanonicalJson = (shapes: readonly Shape[]): readonly Shape[] =>
  [...new Map(shapes.map((shape) => [canonicalJson(shape), shape])).entries()].sort(([left], [right]) => left < right ? -1 : 1).map(([, shape]) => shape);

const shapeOf = (checker: ts.TypeChecker, type: ts.Type, open: ReadonlySet<ts.Type>): Shape => {
  if (type.flags & SCALAR) return checker.typeToString(type);
  if (open.has(type)) return { recursive: checker.typeToString(type, undefined, ts.TypeFormatFlags.NoTruncation) };
  const inner = new Set(open).add(type);
  if (type.isUnion()) return { anyOf: byCanonicalJson(type.types.map((member) => shapeOf(checker, member, inner))) };
  if (checker.isArrayType(type)) return { items: shapeOf(checker, checker.getTypeArguments(type as ts.TypeReference)[0]!, inner) };
  if (checker.isTupleType(type)) return { tuple: checker.getTypeArguments(type as ts.TypeReference).map((element) => shapeOf(checker, element, inner)) };
  if (type.getCallSignatures().length > 0) return "function";
  return {
    object: Object.fromEntries([
      ...checker.getPropertiesOfType(type).map((property) => [
        `${property.name}${property.flags & ts.SymbolFlags.Optional ? "?" : ""}`,
        shapeOf(checker, checker.getTypeOfSymbol(property), inner),
      ]),
      ...checker.getIndexInfosOfType(type).map((index) => [`[${checker.typeToString(index.keyType)}]`, shapeOf(checker, index.type, inner)]),
    ]),
  };
};

const compilerOptions = (root: string): ts.CompilerOptions => {
  const file = path.join(root, "apps/vscode/tsconfig.json");
  const { config, error } = ts.readConfigFile(file, ts.sys.readFile);
  if (error) throw new Error(`${file}: ${ts.flattenDiagnosticMessageText(error.messageText, " ")}`);
  return { ...ts.parseJsonConfigFileContent(config, ts.sys, path.dirname(file)).options, noEmit: true };
};

/** The TypeScript types of every listed contract, as the extension's compiler sees them; an opaque schema such as openJson only has its type. */
const contractShapes = (root: string): readonly Shape[] => {
  const probe = path.join(root, "scripts/vscode/__extension-api-probe__.ts");
  const probeText = [
    `import type { ChannelMessage, ChannelParams, OperationInput, OperationResult } from "../../packages/ragents/src/rpc/contract";`,
    `import type { extensionApi } from "./extension-api";`,
    `type Listed = typeof extensionApi.contracts;`,
    ...extensionApi.contracts.map((contract, index) => contract.kind === "operation"
      ? `export type Shape${index} = { input: OperationInput<Listed[${index}]>; result: OperationResult<Listed[${index}]> };`
      : `export type Shape${index} = { params: ChannelParams<Listed[${index}]>; message: ChannelMessage<Listed[${index}]> };`),
  ].join("\n");
  const options = compilerOptions(root);
  const host = ts.createCompilerHost(options);
  const readSource = host.getSourceFile.bind(host);
  host.getSourceFile = (file, language, onError, create) =>
    path.resolve(file) === probe ? ts.createSourceFile(file, probeText, language, true) : readSource(file, language, onError, create);
  const program = ts.createProgram({ rootNames: [probe], options, host });
  const source = program.getSourceFile(probe)!;
  const diagnostics = program.getSemanticDiagnostics(source);
  if (diagnostics.length > 0) {
    throw new Error(`The types of the listed contracts do not resolve: ${diagnostics.map((diagnostic) => ts.flattenDiagnosticMessageText(diagnostic.messageText, " ")).join("; ")}`);
  }
  const checker = program.getTypeChecker();
  return source.statements.filter(ts.isTypeAliasDeclaration).filter((alias) => alias.name.text.startsWith("Shape"))
    .map((alias) => shapeOf(checker, checker.getTypeAtLocation(alias.name), new Set()));
};

/** A JSON Schema without its prose; a changed description does not change the contract. */
const schemaOf = (value: unknown): unknown => Array.isArray(value) ? value.map(schemaOf)
  : typeof value === "object" && value !== null
    ? Object.fromEntries(Object.entries(value).filter(([key, entry]) => key !== "description" || typeof entry !== "string").map(([key, entry]) => [key, schemaOf(entry)]))
    : value;

const contractHash = (contract: OperationContract | ChannelContract, shape: Shape): string => canonicalHash(contract.kind === "operation"
  ? { kind: contract.kind, implementedBy: contract.implementedBy, input: schemaOf(contract.input), result: schemaOf(contract.result), types: shape }
  : { kind: contract.kind, params: schemaOf(contract.params), message: schemaOf(contract.message), types: shape });

/** The current fingerprint: per contract its kind, schemas, and types, per file its content. */
export const extensionApiRecord = (root: string): ExtensionApiRecord => {
  const ids = extensionApi.contracts.map((contract) => contract.id);
  const twice = ids.filter((id, index) => ids.indexOf(id) !== index);
  if (twice.length > 0) throw new Error(`scripts/vscode/extension-api.ts lists ${twice.join(", ")} more than once`);
  const shapes = contractShapes(root);
  return {
    version: EXTENSION_API_VERSION,
    contracts: Object.fromEntries(extensionApi.contracts.map((contract, index) => [contract.id, contractHash(contract, shapes[index]!)])),
    files: Object.fromEntries(extensionApi.files.map((file) => [file, createHash("sha256").update(readFileSync(path.join(root, file))).digest("hex")])),
  };
};

export const extensionApiRecordFile = (root: string): string => path.join(root, EXTENSION_API_RECORD_FILE);

export const readExtensionApiRecord = (root: string): ExtensionApiRecord => {
  const file = extensionApiRecordFile(root);
  if (!existsSync(file)) throw new Error(`${file} is missing; generate it with pnpm update:extension-api`);
  return JSON.parse(readFileSync(file, "utf8")) as ExtensionApiRecord;
};

export const extensionApiRecordText = (record: ExtensionApiRecord): string => `${JSON.stringify(record, null, 2)}\n`;

export interface ExtensionApiChange {
  readonly part: "contract" | "file";
  readonly name: string;
  readonly change: "added" | "removed" | "changed";
}

const partChanges = (part: ExtensionApiChange["part"], stored: Readonly<Record<string, string>>, current: Readonly<Record<string, string>>): readonly ExtensionApiChange[] =>
  [...new Set([...Object.keys(stored), ...Object.keys(current)])].sort().flatMap((name): readonly ExtensionApiChange[] => stored[name] === current[name] ? []
    : [{ part, name, change: stored[name] === undefined ? "added" : current[name] === undefined ? "removed" : "changed" }]);

/** What differs between two records, contracts first, each part sorted by name. */
export const extensionApiChanges = (stored: ExtensionApiRecord, current: ExtensionApiRecord): readonly ExtensionApiChange[] =>
  [...partChanges("contract", stored.contracts, current.contracts), ...partChanges("file", stored.files, current.files)];

export const describeExtensionApiChange = ({ part, name, change }: ExtensionApiChange): string => `${part} ${name} ${change}`;
