export const referenceConcepts = [
  { id: "agents", label: "Agent teams" },
  { id: "script-actors", label: "TypeScript actors" },
  { id: "subscriptions", label: "Subscriptions" },
  { id: "fifo", label: "Input queue" },
  { id: "stop", label: "Stopping actors" },
  { id: "artifacts", label: "Artifacts and access" },
  { id: "app-navigation", label: "App navigation", entryKind: "walkthrough" },
  { id: "actor-views", label: "Mini-apps" },
  { id: "actor-state", label: "Actor state" },
  { id: "llm-actor-view", label: "LLM actor with view" },
  { id: "actor-chat", label: "Actor chat" },
  { id: "controlled-chat", label: "Controlled chat" },
  { id: "language-servers", label: "Language diagnostics" },
  { id: "primary-actor", label: "Primary actor", entryKind: "any" },
  { id: "start-guide", label: "Start guide", entryKind: "script" },
  { id: "questions", label: "Questions" },
  { id: "todos", label: "To-dos" },
  { id: "journal", label: "Journal inspection" },
  { id: "run-scripts", label: "Run scripts", entryKind: "script" },
  { id: "skills", label: "Skills", entryKind: "skill" },
  { id: "actor-functions", label: "Actor functions" },
  { id: "view-visibility", label: "View visibility" },
  { id: "global-coordinator", label: "Global coordinator", entryKind: "walkthrough" },
  { id: "conversation-reset", label: "Conversation reset", entryKind: "walkthrough" },
  { id: "settings", label: "Settings and model selection", entryKind: "walkthrough" },
  { id: "processes", label: "Process display", entryKind: "walkthrough" },
  { id: "workspace-files", label: "Files and workspace", entryKind: "walkthrough" },
  { id: "restart-recovery", label: "Recovery after restart", entryKind: "walkthrough" },
  { id: "multimodal-input", label: "Multimodal input", entryKind: "walkthrough" },
] as const;
