export const referenceConcepts = [
  { id: "agents", label: "Agententeams" },
  { id: "script-actors", label: "TypeScript-Actors" },
  { id: "subscriptions", label: "Subscriptions" },
  { id: "fifo", label: "Input-Warteschlange" },
  { id: "stop", label: "Actor-Stopp" },
  { id: "artifacts", label: "Artefakte und Zugriff" },
  { id: "tiles", label: "Fläche", entryKind: "walkthrough" },
  { id: "actor-views", label: "Mini-Apps" },
  { id: "actor-state", label: "Actor-Zustand" },
  { id: "llm-actor-view", label: "LLM-Actor mit View" },
  { id: "actor-chat", label: "Actor-Chat" },
  { id: "controlled-chat", label: "Frei gesteuerter Chat" },
  { id: "language-servers", label: "Sprachprüfung" },
  { id: "primary-actor", label: "Primary-Actor", entryKind: "any" },
  { id: "start-guide", label: "Startleitfaden", entryKind: "script" },
  { id: "questions", label: "Rückfragen" },
  { id: "todos", label: "To-dos" },
  { id: "journal", label: "Journalprüfung" },
  { id: "run-scripts", label: "Run-Scripts", entryKind: "script" },
  { id: "skills", label: "Skills", entryKind: "skill" },
  { id: "actor-functions", label: "Actor-Funktionen" },
  { id: "view-placement", label: "Automatische View-Platzierung" },
  { id: "view-visibility", label: "View-Sichtbarkeit" },
  { id: "global-coordinator", label: "Globaler Koordinator", entryKind: "walkthrough" },
  { id: "conversation-reset", label: "Gesprächsreset", entryKind: "walkthrough" },
  { id: "settings", label: "Einstellungen und Modellwahl", entryKind: "walkthrough" },
  { id: "processes", label: "Prozessanzeige", entryKind: "walkthrough" },
  { id: "workspace-files", label: "Dateien und Arbeitsverzeichnis", entryKind: "walkthrough" },
  { id: "restart-recovery", label: "Wiederherstellung nach Neustart", entryKind: "walkthrough" },
  { id: "multimodal-input", label: "Multimodale Eingaben", entryKind: "walkthrough" },
] as const;
