export const referenceWalkthroughs = [
  {
    id: "mini-app-owner-inspector",
    title: "Den Helfer hinter einer Mini-App öffnen",
    description: "Die Mini-App bleibt auf der Fläche; ihr Besitzer ist auch ohne zusätzliche Karte erreichbar.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Persönliche Canvas-Ansicht"],
    steps: [
      "Im Profil core Sammelboard einrichten öffnen und den Leitfaden abschließen. Erwartung: Die Liste steht auf dem Canvas; die Karte ihres Besitzers ist in der Standardansicht ausgeblendet.",
      "Unten Actors öffnen und den Namen des Listenbesitzers wählen. Erwartung: Rechts öffnen sich dessen Chat und Details, ohne eine zusätzliche Karte einzublenden.",
      "In der Actorliste die Canvas-Sichtbarkeit dieses Actors einschalten. Erwartung: Seine Karte erscheint zusätzlich; die Mini-App bleibt bedienbar und behält ihre Einträge.",
      "Die Karte wieder ausblenden und die App erneut bedienen. Erwartung: Actor und Funktionen arbeiten weiter. Unter Ansicht hebt Ansicht zurücksetzen die persönliche Einzelentscheidung wieder auf.",
    ],
  },
  {
    id: "personal-conversation-canvas",
    title: "Eine Gesprächsrunde übersichtlicher anzeigen",
    description: "Actor-Karten und Verbindungen lassen sich persönlich ausblenden, ohne den Gesprächsaufbau zu verändern.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Persönliche Canvas-Ansicht"],
    steps: [
      "Im Profil core den Skill-Einstieg Eine Gesprächsrunde auf der Fläche anordnen ausführen und den Aufbau abwarten. Die sichtbaren Karten und Verbindungen ansehen.",
      "Unter Actors einen Gesprächspartner vom Canvas ausblenden. Erwartung: Seine Karte und ihre Verbindungen verschwinden; sein Name in der Liste öffnet weiterhin den Inspector. Die übrigen Beteiligten arbeiten weiter.",
      "Unter Ansicht Verbindungen anzeigen ausschalten und denselben Run im selben Browser neu laden. Erwartung: Die persönliche Auswahl bleibt erhalten; die Actors und das gespeicherte Layout sind unverändert.",
      "Unter Ansicht Ansicht zurücksetzen wählen. Erwartung: Verbindungen und gewöhnliche Actor-Karten erscheinen wieder; Actors mit eigener Mini-App bleiben nach der Standardvorgabe ausgeblendet. Bei einem gestoppten Actor bleiben sein Name und sein Verlauf in der Liste erreichbar.",
    ],
  },
  {
    id: "global-run-overview",
    title: "Zwei Unterhaltungen im Blick behalten",
    description: "Der übergeordnete Koordinator liest vorhandene Runs, während die aktuelle Arbeitsfläche geöffnet bleibt.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Globaler Koordinator"],
    steps: [
      "Im Profil core zwei kurze Unterhaltungen zu einer Leseliste und einem Wochenplan anlegen und ihre Antworten abwarten.",
      "In die Eingabe Globaler Koordinator in der Kopfzeile klicken und damit seinen Verlauf öffnen. Um eine knappe Übersicht der beiden Unterhaltungen mit ihrem jeweiligen Arbeitsstand bitten.",
      "Die Run-Liste über die Übersichtsecke oder Cmd+I auf macOS beziehungsweise Ctrl+I öffnen, beide Runs auswählen und die Antwort mit ihren tatsächlichen Unterhaltungen vergleichen. Erwartung: Der globale Chat kann beide Journale berücksichtigen; ein Run-Wechsel erhält seinen eigenen Verlauf.",
      "Einen ungesendeten Entwurf oben eingeben, Escape drücken und den Verlauf wieder öffnen. Erwartung: Das Dropdown schließt ohne Stopp; Entwurf, aktueller Run und globales Gespräch bleiben erhalten.",
    ],
  },
  {
    id: "global-prepared-run",
    title: "Eine vorbereitete Runde global starten",
    description: "Der übergeordnete Koordinator wählt aus dem vorhandenen Katalog ein Run-Script und erstellt damit einen neuen Run.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Globaler Koordinator"],
    steps: [
      "In die Eingabe Globaler Koordinator in der Kopfzeile klicken und bitten: Zeige die verfügbaren vorbereiteten Run-Scripts und starte Gesprächsrunde einrichten zum Thema gemeinsames Lernen mit zwei Runden.",
      "Nach dem Senden die Kurzantwort direkt unter der Kopfzeile abwarten. Den Hinweis anklicken und die vollständige Antwort im Verlauf lesen. Falls der Startwert unklar ist, die Rückfrage anhand des angezeigten Katalogs beantworten; keine Modellkennung oder Run-ID abschreiben.",
      "Den neuen Run über die Run-Liste öffnen. Erwartung: Ein eigener Run mit dem angeforderten Thema und dem vorbereiteten Aufbau entsteht. Die Annahme des Starts allein beweist noch keinen abgeschlossenen Gesprächsbeitrag.",
      "Nach dem ersten tatsächlichen Beitrag unten Actors öffnen und einen Gesprächspartner im Inspector auswählen. Oben im globalen Chat fragen: Was macht dieser Actor? Erwartung: Die Frage erhält den Run und den ausgewählten Actor als getrennte Orientierung; der sichtbare Fragetext bleibt unverändert.",
      "Nach dem Absenden einen anderen Run öffnen. Erwartung: Die bereits gesendete Frage bleibt an ihre ursprüngliche Auswahl gebunden, auch wenn sie erst später bearbeitet wird. Der globale Verlauf und beide Runs bleiben getrennt erreichbar.",
    ],
  },
  {
    id: "reset-completed-global-chat",
    title: "Nach einer Planung neu beginnen",
    description: "Ein bestätigter Reset leert das globale Gespräch und lässt bestehende Runs und die Modellauswahl erhalten.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Gesprächsreset"],
    steps: [
      "Im globalen Chat eine kurze Planung abschließen. Einen normalen Run geöffnet lassen und die aktuelle globale Modell- und Reasoningwahl merken.",
      "Gespräch zurücksetzen wählen und die angezeigte Bestätigung ausdrücklich bestätigen. Die erfolgreiche Rückmeldung abwarten.",
      "Erwartung: Verlauf, Eingabeentwurf und Anhänge des globalen Chats sind leer; der geöffnete normale Run sowie die Modell- und Reasoningwahl bestehen weiter.",
      "Eine neue kurze Nachricht senden. Erwartung: Sie beginnt ein frisches globales Gespräch. Der Reset selbst hat keinen neuen Modellauftrag gestartet.",
    ],
  },
  {
    id: "reset-without-losing-draft",
    title: "Einen Reset zunächst abbrechen",
    description: "Die Bestätigung schützt einen noch benötigten Gesprächsentwurf; erst der bestätigte zweite Versuch leert ihn.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Gesprächsreset"],
    steps: [
      "Im globalen Chat einen kurzen Entwurf eingeben, ohne ihn zu senden. Gespräch zurücksetzen öffnen und die Bestätigung abbrechen.",
      "Erwartung: Entwurf und bestehender Verlauf bleiben erhalten. Die bloße Anzeige der Bestätigung setzt nichts zurück.",
      "Gespräch zurücksetzen erneut öffnen und diesmal bestätigen. Während des Resets keine weitere Nachricht senden.",
      "Erwartung: Nach Erfolg sind Entwurf und Verlauf leer. Bei einem Fehler bleibt dessen Meldung sichtbar und erlaubt einen erneuten Versuch; ein Fehler darf nicht als erfolgreicher Reset gelten.",
    ],
  },
  {
    id: "coordinator-model-settings",
    title: "Den Koordinator für kurze Antworten einstellen",
    description: "Modell und Reasoning werden direkt im globalen Chat gewählt und in den Einstellungen wiedergefunden.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Einstellungen und Modellwahl"],
    steps: [
      "Den globalen Verlauf über die Toolbar-Eingabe öffnen und im Dropdown oberhalb des Verlaufs ein angebotenes Modell und eine dort verfügbare Reasoning-Stufe wählen. Keine nicht angebotene Stufe voraussetzen.",
      "Die bestätigte Speicherung abwarten und danach eine kurze Frage stellen. Erwartung: Neue Arbeit verwendet die gespeicherte Auswahl; ein schon laufender Turn wird dadurch nicht rückwirkend verändert.",
      "Das Zahnrad öffnen und unter Modelle die Einstellung Globaler Koordinator ansehen. Erwartung: Beide Ansichten zeigen dieselbe bestätigte Auswahl.",
      "Falls ein Modellwechsel wegen bereits vorhandener Medien abgelehnt wird, die sichtbare Fehlermeldung beachten. Erwartung: Die bisherige gültige Auswahl bleibt erhalten.",
    ],
  },
  {
    id: "title-model-selection",
    title: "Das Modell für kurze Überschriften wählen",
    description: "Ein eigenes Modell verdichtet den Auftrag in der Run-Liste, ohne die Modelle der Agenten zu ändern.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Einstellungen und Modellwahl"],
    steps: [
      "Über das Zahnrad Einstellungen, Modelle und Überschriften öffnen. Bei einer großen Liste mit der Suche ein angebotenes Modell finden, auswählen und Speichern wählen.",
      "Die bestätigte Speicherung abwarten. Erwartung: Die Auswahl bleibt im Formular erhalten; Globaler Koordinator sowie Neue Runs und Agenten behalten ihre eigenen Einstellungen.",
      "Eine neue Unterhaltung mit einem ausführlicheren Auftrag beginnen und die Run-Liste öffnen. Erwartung: Der ursprüngliche Auftrag ist bereits sichtbar. Sobald ein automatischer Titel erfolgreich erzeugt und gespeichert ist, erscheint die kurze Überschrift ohne zusätzlichen manuellen Listenabruf. Eine feste Antwortzeit wird nicht vorausgesetzt.",
      "Eine andere Modellwahl als Entwurf einstellen und Änderungen verwerfen wählen. Erwartung: Die bestätigte Auswahl kehrt zurück; ein schon erzeugter Titel wird nicht ersetzt.",
    ],
  },
  {
    id: "disable-generated-titles",
    title: "Automatische Überschriften ausschalten",
    description: "Neue Erzeugungen lassen sich deaktivieren; vorhandene und ausdrücklich gesetzte Titel bleiben erhalten.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Einstellungen und Modellwahl"],
    steps: [
      "Eine Unterhaltung mit bereits erzeugtem Kurztitel in der Run-Liste ansehen. Unter Einstellungen, Modelle, Überschriften Keine automatischen Überschriften auswählen und speichern.",
      "Die Anwendung neu laden und die Einstellung erneut ansehen. Erwartung: Die Deaktivierung ist gespeichert; der bestehende Kurztitel bleibt unverändert.",
      "Eine weitere Unterhaltung mit einem normalen Auftrag beginnen. Erwartung: Die Run-Liste zeigt den Auftrag, ohne dafür einen automatischen Kurztitel anzufordern.",
      "Optional Sammelboard einrichten starten und im Leitfaden einen Namen vorgeben. Erwartung: Der vorbereitete Ablauf setzt weiterhin seinen eigenen Run-Titel. Ein später wieder aktiviertes Titelmodell überschreibt diesen Namen nicht.",
    ],
  },
  {
    id: "extension-capability-settings",
    title: "Eine Fähigkeit ihrer Extension zuordnen",
    description: "Die beiden Ansichten der Einstellungen erschließen denselben Bestand aus unterschiedlichen Richtungen.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Einstellungen und Modellwahl"],
    steps: [
      "Über das Zahnrad die Einstellungen öffnen und zu Erweiterungen wechseln. In Nach Extension die Actor-Programm-Extension auswählen und ihre Werkzeuge und Web-Beiträge ansehen.",
      "Zu Nach Fähigkeit wechseln, Werkzeuge auswählen und nach actor_program suchen. Erwartung: Die passenden Beiträge erscheinen mit ihrer jeweiligen Extension als Eigentümer.",
      "Den Link zur Actor-Programm-Extension öffnen. Erwartung: Ihr vollständiges Inventar ist wieder sichtbar; ein vorheriger Suchfilter verdeckt die Detailseite nicht.",
      "Zu Modelle wechseln und die Koordinator-Modellwahl öffnen. Nur tatsächlich angebotene Werte sind wählbar; eine ungültige Kombination wird nicht still ersetzt.",
    ],
  },
  {
    id: "language-server-process",
    title: "Den Sprachserver als Run-Prozess sehen",
    description: "Eine TypeScript-Prüfung macht den zugehörigen Sprachserver in der Prozessanzeige sichtbar.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Prozessanzeige"],
    steps: [
      "Im Profil core den Skill-Einstieg Fehler in einer Terminliste finden ausführen. Voraussetzung ist ein verfügbarer TypeScript-Sprachserver; eine fehlende Voraussetzung muss als Fehler gemeldet werden.",
      "Nach dem Öffnen des Sprachservers die gemeinsame Kopfzeile des Runs ansehen. Erwartung: Der verwaltete Sprachserver erscheint als zu diesem Run gehörender Prozess.",
      "Einen anderen Run öffnen und zurückwechseln. Erwartung: Die Prozessanzeige folgt dem ausgewählten Run und ist kein gemeinsames Verzeichnis aller Rechnerprozesse.",
      "Die Prozessanzeige dient der Beobachtung. Sie bietet keinen Beenden-Knopf; fehlende Betriebssystemrechte oder Werkzeuge werden als sichtbarer Fehler gemeldet.",
    ],
  },
  {
    id: "local-preview-process",
    title: "Eine kurzlebige lokale Vorschau öffnen",
    description: "Ein zeitlich begrenzter Demo-Webprozess erscheint mit seinem erkannten Port in der Kopfzeile.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Prozessanzeige"],
    steps: [
      "In einem eigenen core-Run den Koordinator bitten, einen kleinen Node-Demoprozess im Run-Arbeitsverzeichnis vorzubereiten: Er liefert nur einen neutralen Begrüßungstext, bindet ausschließlich 127.0.0.1 auf einem freien Port und beendet sich nach zwei Minuten selbst. Keine zusätzlichen Pakete installieren und keinen Produktserver ersetzen.",
      "Den vorbereiteten Demoprozess starten lassen und bei laufender Ausführung die Kopfzeile ansehen. Erwartung: Der Prozess erscheint mit einem Link auf seinen erkannten offenen Port.",
      "Den Port-Link nur auf demselben Rechner öffnen. Erwartung: Die lokale Demoantwort erscheint; bei einem entfernten Server ist dessen Loopback-Adresse nicht die Adresse des Browsers.",
      "Das vorgesehene automatische Ende abwarten. Erwartung: Der Eintrag verschwindet nach der nächsten Prozessaktualisierung. Run-Stopp oder das Schließen eines Tabs werden hier nicht als Beenden eines abgesetzten Dienstes versprochen.",
    ],
  },
  {
    id: "workspace-draft-preview",
    title: "Einen Entwurf im Dateibaum lesen",
    description: "Ein Run schreibt einen kleinen Text; der Dateireiter zeigt Inhalt und spätere Änderung ohne eigenen Editor.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Dateien und Arbeitsverzeichnis"],
    steps: [
      "In einem neuen core-Run den Koordinator bitten, im Run-Arbeitsverzeichnis die Datei reading-list.md mit drei neutralen Lesethemen anzulegen.",
      "Den Reiter Dateien öffnen, das Arbeitsverzeichnis aufklappen und reading-list.md auswählen. Erwartung: Der geschriebene Text erscheint als Vorschau.",
      "Im Chat ein viertes Thema ergänzen lassen und zur weiterhin geöffneten Vorschau zurückkehren. Erwartung: Die Dateiänderung wird im Dateibrowser sichtbar.",
      "Erwartung: Der Dateireiter bleibt eine Leseansicht. Änderungen erfolgen durch den beauftragten Actor und dessen Dateiwerkzeuge, nicht durch einen eingebauten Editor oder Löschknopf.",
    ],
  },
  {
    id: "separate-run-files",
    title: "Gleichnamige Dateien in zwei Runs vergleichen",
    description: "Zwei unabhängige Arbeitsverzeichnisse enthalten eigene Dateien mit demselben Namen.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Dateien und Arbeitsverzeichnis"],
    steps: [
      "Einen core-Run Leseliste anlegen und darin notes.md mit dem Inhalt Lesen vorbereiten schreiben lassen.",
      "Einen zweiten core-Run Wochenplan anlegen und dort ebenfalls notes.md schreiben lassen, diesmal mit dem Inhalt Woche planen. Keine Datei zwischen Runs kopieren.",
      "In beiden Runs nacheinander den Reiter Dateien öffnen und notes.md lesen. Erwartung: Der gleiche Dateiname zeigt den jeweils eigenen Inhalt des Run-Arbeitsverzeichnisses.",
      "Nur im Wochenplan eine Zeile ergänzen lassen und beide Vorschauen erneut prüfen. Erwartung: Die Datei des Leselisten-Runs ist unverändert.",
    ],
  },
  {
    id: "restore-shared-list",
    title: "Eine gemeinsame Liste nach Neustart wiederfinden",
    description: "Eine abgeschlossene Actor-Funktion bleibt beim regulären Neustart desselben Profils erhalten.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Wiederherstellung nach Neustart"],
    steps: [
      "Im Profil core Sammelboard einrichten öffnen und den Leitfaden abschließen. Einen eindeutig erkennbaren Eintrag hinzufügen und die bestätigte Aktualisierung der Liste abwarten.",
      "Alle laufenden Arbeiten abschließen lassen. Den lokalen Server selbst über den für diese Installation verwendeten Startweg beenden und mit demselben Profil und Datenverzeichnis neu starten. Keine Daten löschen und keine zweite Serverinstanz parallel starten.",
      "Die Anwendung erneut öffnen und denselben Run auswählen. Erwartung: Gespräch, Mini-App und bestätigter Listeneintrag sind wieder vorhanden.",
      "Die Liste auf doppelte Einträge prüfen. Erwartung: Der Neustart stellt gespeicherten Zustand wieder her, führt die bereits abgeschlossene Hinzufügeaktion aber nicht erneut aus. Das Journal allein ersetzt keine vollständige Sicherung der übrigen Run-Dateien.",
    ],
  },
  {
    id: "restore-conversation-context",
    title: "Zwei Gesprächsverläufe nach Neustart fortsetzen",
    description: "Normale Unterhaltung und globaler Koordinator behalten ihre jeweils eigene Geschichte.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Wiederherstellung nach Neustart"],
    steps: [
      "In einem normalen core-Run drei Lernziele besprechen und im globalen Chat eine knappe Übersicht dieses Runs anfordern. Beide Antworten vollständig abwarten und die globale Modellwahl merken.",
      "Den lokalen Server selbst über den vorhandenen Startweg neu starten, mit demselben Profil und Datenverzeichnis. Keine Dateien entfernen oder zwischen Installationen übertragen.",
      "Den normalen Run und anschließend den globalen Chat öffnen. Erwartung: Beide bisherigen Verläufe und die globale Modellwahl sind erhalten.",
      "Im normalen Run um den nächsten Schritt zu den Lernzielen bitten. Die neue Antwort als neue Arbeit behandeln; der Neustart hat alte Modellaufrufe nicht wiederholt. Ein beim Neustart noch offener Turn wäre unterbrochen abgeschlossen worden und wird nicht automatisch erneut ausgeführt.",
    ],
  },
  {
    id: "image-paste-conversation",
    title: "Eine eigene Skizze im Chat besprechen",
    description: "Ein Bild aus der Zwischenablage wird vor dem Senden geprüft und danach als Anhang im Verlauf gezeigt.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Multimodale Eingaben"],
    steps: [
      "Eine eigene unkritische Skizze in die Zwischenablage kopieren. Eine neue Unterhaltung öffnen und ein angebotenes Modell wählen, das Bildeingaben unterstützt.",
      "Das Bild mit Cmd+V oder Ctrl+V in die Chat-Eingabe einfügen. Erwartung: Eine Bildvorschau erscheint, lässt sich vor dem Senden wieder entfernen und wurde noch nicht allein durch das Einfügen gesendet.",
      "Mit der Frage Welche drei Formen erkennst du? senden. Erwartung: Nach erfolgreicher Annahme stehen Nachricht und dauerhafter Bildanhang im Verlauf; die Antwort wird gegen die tatsächliche Skizze geprüft.",
      "Falls das Zielmodell keine Bildeingaben unterstützt, muss der Composer das Senden mit einer verständlichen Meldung blockieren. Kein passendes Modell im Katalog ist eine fehlende Voraussetzung, kein Anlass für einen behaupteten Bildbefund.",
    ],
  },
  {
    id: "video-and-document-drop",
    title: "Einen kurzen Clip mit seinem Ablaufplan vergleichen",
    description: "Video und PDF werden per Drag-and-drop ausdrücklich an ein geeignetes Modell gesendet.",
    tags: ["Anwendungsfall", "Konzeptdemo", "Multimodale Eingaben"],
    steps: [
      "Einen eigenen kurzen, unkritischen Videoclip und einen kleinen PDF-Ablaufplan bereitlegen. Einen Chat mit einem angebotenen Modell öffnen, dessen veröffentlichte Eingabefähigkeiten sowohl Video als auch native PDFs erlauben. Gibt es kein solches Modell, ist dieser Ablauf nicht ausführbar.",
      "Beide Dateien in die Chat-Eingabe ziehen. Erwartung: Der Clip erhält eine Vorschau und das PDF eine Dateiangabe; Anhänge lassen sich einzeln entfernen. Sichtbare Größen- oder Fähigkeitsfehler vor dem Senden beheben.",
      "Mit der Frage Welche geplanten Schritte sind im Clip sichtbar? senden und die tatsächliche Antwort mit Clip und Ablaufplan vergleichen. Erwartung: Die Anhänge bleiben im Verlauf erneut erreichbar.",
      "Bei fehlender Video- oder PDF-Unterstützung bleibt das Senden blockiert. Es gibt hier keine stille OCR-Ausweichverarbeitung und keine Zusage, dass jedes angebotene Modell die Dateien versteht.",
    ],
  },
];
