export const referenceWalkthroughs = [
  {
    id: "mini-app-owner-inspector",
    title: "Open the helper behind a mini-app",
    description: "The mini-app stays visible as a tile; its owner is reachable even without a tile of its own.",
    tags: ["Use case", "Concept demo", "Surface"],
    steps: [
      "In the showcase profile, open Set up collection board and complete the guide. Expected: The list is a tile on the surface; its owner has no tile of its own.",
      "Open Actors in the header and choose the name of the list owner. Expected: Its chat and details open on the right without changing the tile layout.",
      "Drag the owner from the header onto the list tile and dock it on the right. Expected: Its tile appears next to the list; the mini-app stays usable and keeps its entries.",
      "Remove the new tile again with the cross in its title bar and use the app again. Expected: The actor and its functions keep working; its name stays reachable in the header.",
    ],
  },
  {
    id: "personal-tile-arrangement",
    title: "Split a conversation circle differently",
    description: "Tiles can be rearranged personally and reset to the program default.",
    tags: ["Use case", "Concept demo", "Surface"],
    steps: [
      "In the showcase profile, run the template Set up conversation circle and wait for the setup. Look at the layout set by the run.",
      "Grab a tile by its title bar and dock it at the top edge of another tile. Expected: The layout changes immediately; all conversation partners keep working.",
      "Move the divider between two tiles and reload the same run in the same browser. Expected: The personal layout is kept; the actors and the program arrangement are unchanged.",
      "Choose Apply program default in the status bar. Expected: The surface shows the run's layout again; the button disappears until there is another change of your own.",
    ],
  },
  {
    id: "global-run-overview",
    title: "Keep an eye on two runs",
    description: "The global coordinator reads existing runs while the current surface stays open.",
    tags: ["Use case", "Concept demo", "Global coordinator"],
    steps: [
      "In the showcase profile, create two short runs about a reading list and a weekly plan and wait for their answers.",
      "Click the Global coordinator input in the header to open its history. Ask for a brief overview of both runs with their current progress.",
      "Open the run list via the overview corner or Cmd+I on macOS or Ctrl+I, select both runs, and compare the answer with their actual conversations. Expected: The global chat can take both journals into account; switching runs keeps its own history.",
      "Type an unsent draft at the top, press Escape, and open the history again. Expected: The dropdown closes without stopping anything; the draft, the current run, and the global conversation are kept.",
    ],
  },
  {
    id: "global-prepared-run",
    title: "Start a prepared circle globally",
    description: "The global coordinator picks a run script from the existing catalog and creates a new run with it.",
    tags: ["Use case", "Concept demo", "Global coordinator"],
    steps: [
      "Click the Global coordinator input in the header and ask: Show the available prepared run scripts and start Set up conversation circle on the topic of learning together with two rounds.",
      "After sending, wait for the short answer directly below the header. Click the notice and read the full answer in the history. If the start value is unclear, answer the question based on the catalog shown; do not copy a model id or run id.",
      "Open the new run from the run list. Expected: A separate run with the requested topic and the prepared setup is created. Acceptance of the start alone does not prove a completed conversation contribution.",
      "After the first actual contribution, open Actors at the bottom and select a conversation partner in the inspector. At the top of the global chat, ask: What does this actor do? Expected: The question receives the run and the selected actor as separate orientation; the visible question text stays unchanged.",
      "After sending, open another run. Expected: The question already sent stays bound to its original selection, even if it is processed only later. The global history and both runs stay reachable separately.",
    ],
  },
  {
    id: "reset-completed-global-chat",
    title: "Start over after planning",
    description: "A confirmed reset clears the global conversation and keeps existing runs and the model selection.",
    tags: ["Use case", "Concept demo", "Conversation reset"],
    steps: [
      "Complete a short planning session in the global chat. Keep a normal run open and note the current global model and reasoning selection.",
      "Choose Reset conversation and explicitly confirm the confirmation shown. Wait for the success message.",
      "Expected: The history, input draft, and attachments of the global chat are empty; the open normal run and the model and reasoning selection remain.",
      "Send a new short message. Expected: It starts a fresh global conversation. The reset itself did not start a new model task.",
    ],
  },
  {
    id: "reset-without-losing-draft",
    title: "Cancel a reset at first",
    description: "The confirmation protects a conversation draft you still need; only the confirmed second attempt clears it.",
    tags: ["Use case", "Concept demo", "Conversation reset"],
    steps: [
      "Type a short draft in the global chat without sending it. Open Reset conversation and cancel the confirmation.",
      "Expected: The draft and the existing history are kept. Merely showing the confirmation resets nothing.",
      "Open Reset conversation again and confirm this time. Do not send another message during the reset.",
      "Expected: After success, the draft and history are empty. On an error, its message stays visible and allows a retry; an error must not count as a successful reset.",
    ],
  },
  {
    id: "coordinator-model-settings",
    title: "Set up the coordinator for short answers",
    description: "Model and reasoning are chosen directly in the global chat and can be found again in the settings.",
    tags: ["Use case", "Concept demo", "Settings and model selection"],
    steps: [
      "Open the global history via the toolbar input and, in the dropdown above the history, choose an offered model and a reasoning level available there. Do not assume a level that is not offered.",
      "Wait for the confirmed save and then ask a short question. Expected: New work uses the saved selection; a turn that is already running is not changed retroactively.",
      "Open the gear and look at the Global coordinator setting under Models. Expected: Both views show the same confirmed selection.",
      "If a model change is rejected because of media that already exists, note the visible error message. Expected: The previous valid selection is kept.",
    ],
  },
  {
    id: "title-model-selection",
    title: "Choose the model for short titles",
    description: "A separate model condenses the task in the run list without changing the agents' models.",
    tags: ["Use case", "Concept demo", "Settings and model selection"],
    steps: [
      "Open Settings, Models, and Titles via the gear. With a large list, use the search to find an offered model, select it, and choose Save.",
      "Wait for the confirmed save. Expected: The selection stays in the form; Global coordinator as well as New runs and agents keep their own settings.",
      "Start a new run with a more detailed task and open the run list. Expected: The original task is already visible. As soon as an automatic title has been generated and saved successfully, the short title appears without an additional manual list refresh. No fixed response time is assumed.",
      "Set a different model selection as a draft and choose Discard changes. Expected: The confirmed selection returns; a title that was already generated is not replaced.",
    ],
  },
  {
    id: "disable-generated-titles",
    title: "Turn off automatic titles",
    description: "New generation can be disabled; existing and explicitly set titles are kept.",
    tags: ["Use case", "Concept demo", "Settings and model selection"],
    steps: [
      "Look at a run with an already generated short title in the run list. Under Settings, Models, Titles, select No automatic titles and save.",
      "Reload the application and look at the setting again. Expected: The deactivation is saved; the existing short title stays unchanged.",
      "Start another run with a normal task. Expected: The run list shows the task without requesting an automatic short title for it.",
      "Optionally start Set up collection board and enter a name in the guide. Expected: The prepared flow still sets its own run title. A title model that is enabled again later does not overwrite this name.",
    ],
  },
  {
    id: "extension-capability-settings",
    title: "Map a capability to its plugin",
    description: "The two views of the settings open up the same inventory from different directions.",
    tags: ["Use case", "Concept demo", "Settings and model selection"],
    steps: [
      "Open the settings via the gear and switch to Plugins. In By plugin, select the actor program plugin and look at its tools and web contributions.",
      "Switch to By capability, select Tools, and search for actor_program. Expected: The matching contributions appear with their respective plugin as owner.",
      "Open the link to the actor program plugin. Expected: Its complete inventory is visible again; a previous search filter does not hide the detail page.",
      "Switch to Models and open the coordinator model selection. Only values that are actually offered can be selected; an invalid combination is not silently replaced.",
    ],
  },
  {
    id: "language-server-process",
    title: "See the language server as a run process",
    description: "A TypeScript check makes the associated language server visible in the process display.",
    tags: ["Use case", "Concept demo", "Process display"],
    steps: [
      "In the showcase profile, run the skill template Find errors in an appointment list. It requires an available TypeScript language server; a missing prerequisite must be reported as an error.",
      "After the language server has been opened, look at the run's shared header. Expected: The managed language server appears as a process belonging to this run.",
      "Open another run and switch back. Expected: The process display follows the selected run and is not a shared list of all processes on the machine.",
      "The process display is for observation. It offers no stop button; missing operating system permissions or tools are reported as a visible error.",
    ],
  },
  {
    id: "local-preview-process",
    title: "Open a short-lived local preview",
    description: "A time-limited demo web process appears in the header with its detected port.",
    tags: ["Use case", "Concept demo", "Process display"],
    steps: [
      "In a separate showcase run, ask the coordinator to prepare a small Node demo process in the run workspace: It only serves a neutral greeting text, binds exclusively to 127.0.0.1 on a free port, and exits by itself after two minutes. Do not install additional packages and do not replace a product server.",
      "Have the prepared demo process started and look at the header while it runs. Expected: The process appears with a link to its detected open port.",
      "Open the port link only on the same machine. Expected: The local demo response appears; with a remote server, its loopback address is not the browser's address.",
      "Wait for the intended automatic end. Expected: The entry disappears after the next process refresh. Stopping the run or closing a tab is not promised here to end a detached service.",
    ],
  },
  {
    id: "workspace-draft-preview",
    title: "Read a draft in the file tree",
    description: "A run writes a small text; the files tab shows its content and a later change without an editor of its own.",
    tags: ["Use case", "Concept demo", "Files and workspace"],
    steps: [
      "In a new showcase run, ask the coordinator to create the file reading-list.md with three neutral reading topics in the run workspace.",
      "Open the Files tab, expand the workspace, and select reading-list.md. Expected: The written text appears as a preview.",
      "Have a fourth topic added in the chat and return to the preview that is still open. Expected: The file change becomes visible in the file browser.",
      "Expected: The files tab stays a read-only view. Changes are made by the assigned actor and its file tools, not by a built-in editor or delete button.",
    ],
  },
  {
    id: "separate-run-files",
    title: "Compare files with the same name in two runs",
    description: "Two independent workspaces contain their own files with the same name.",
    tags: ["Use case", "Concept demo", "Files and workspace"],
    steps: [
      "Create a showcase run Reading list and have it write notes.md with the content Prepare reading.",
      "Create a second showcase run Weekly plan and have it also write notes.md, this time with the content Plan the week. Do not copy any file between runs.",
      "Open the Files tab in both runs one after the other and read notes.md. Expected: The same file name shows the respective content of each run workspace.",
      "Have a line added only in the weekly plan and check both previews again. Expected: The file of the reading list run is unchanged.",
    ],
  },
  {
    id: "restore-shared-list",
    title: "Find a shared list again after a restart",
    description: "A completed actor function is kept when the same profile is restarted normally.",
    tags: ["Use case", "Concept demo", "Recovery after restart"],
    steps: [
      "In the showcase profile, open Set up collection board and complete the guide. Add a clearly recognizable entry and wait for the confirmed update of the list.",
      "Let all running work finish. Stop the local server yourself using the start method used for this installation and restart it with the same profile and data directory. Do not delete any data and do not start a second server instance in parallel.",
      "Open the application again and select the same run. Expected: The conversation, the mini-app, and the confirmed list entry are present again.",
      "Check the list for duplicate entries. Expected: The restart restores the saved state but does not run the already completed add action again. The journal alone does not replace a complete backup of the other run files.",
    ],
  },
  {
    id: "restore-conversation-context",
    title: "Continue two conversation histories after a restart",
    description: "A normal run and the global coordinator each keep their own history.",
    tags: ["Use case", "Concept demo", "Recovery after restart"],
    steps: [
      "In a normal showcase run, discuss three learning goals and request a brief overview of this run in the global chat. Wait for both answers to complete and note the global model selection.",
      "Restart the local server yourself using the existing start method, with the same profile and data directory. Do not remove any files or transfer them between installations.",
      "Open the normal run and then the global chat. Expected: Both previous histories and the global model selection are kept.",
      "In the normal run, ask for the next step on the learning goals. Treat the new answer as new work; the restart did not repeat old model calls. A turn that was still open during the restart would have been completed as interrupted and is not run again automatically.",
    ],
  },
  {
    id: "image-paste-conversation",
    title: "Discuss your own sketch in the chat",
    description: "An image from the clipboard is checked before sending and then shown as an attachment in the history.",
    tags: ["Use case", "Concept demo", "Multimodal input"],
    steps: [
      "Copy a harmless sketch of your own to the clipboard. Open a new run and choose an offered model that supports image input.",
      "Paste the image into the chat input with Cmd+V or Ctrl+V. Expected: An image preview appears, can be removed again before sending, and has not been sent merely by pasting.",
      "Send with the question Which three shapes do you recognize? Expected: After successful acceptance, the message and a persistent image attachment are in the history; the answer is checked against the actual sketch.",
      "If the target model does not support image input, the composer must block sending with an understandable message. No matching model in the catalog is a missing prerequisite, not a reason for a claimed image finding.",
    ],
  },
  {
    id: "video-and-document-drop",
    title: "Compare a short clip with its schedule",
    description: "Video and PDF are explicitly sent to a suitable model via drag and drop.",
    tags: ["Use case", "Concept demo", "Multimodal input"],
    steps: [
      "Prepare a short, harmless video clip of your own and a small PDF schedule. Open a chat with an offered model whose published input capabilities allow both video and native PDFs. If there is no such model, this flow cannot be run.",
      "Drag both files into the chat input. Expected: The clip gets a preview and the PDF a file label; attachments can be removed individually. Fix visible size or capability errors before sending.",
      "Send with the question Which planned steps are visible in the clip? and compare the actual answer with the clip and the schedule. Expected: The attachments stay reachable again in the history.",
      "Without video or PDF support, sending stays blocked. There is no silent OCR fallback here and no promise that every offered model understands the files.",
    ],
  },
];
