import { readFileSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { HOST_API_VERSION, hostApiModules } from "./host-api.js";

export const hostRoot = (): string => path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

/** The value names of the host API and its number, relative to the host root; generated by pnpm update:host-api. */
export const HOST_API_RECORD_FILE = "apps/server/src/host-api.json";

/** The host API number of a host anywhere; this way the extension also checks a host that is not itself. */
export const readHostApiVersion = (root: string = hostRoot()): number => {
  const file = path.join(root, HOST_API_RECORD_FILE);
  if (!statSync(file, { throwIfNoEntry: false })?.isFile()) throw new Error(`The host API is unknown: ${file} is missing`);
  const version = (JSON.parse(readFileSync(file, "utf8")) as { version?: unknown }).version;
  if (typeof version !== "number" || !Number.isInteger(version) || version < 1) throw new Error(`${file}: version is not a host API number`);
  return version;
};

/** The value names each module of the host API offers at runtime, per half; the build tool generates the web shims from it. */
export interface HostApiRecord {
  readonly version: number;
  readonly server: Readonly<Record<string, readonly string[]>>;
  readonly web: Readonly<Record<string, readonly string[]>>;
}

export const readHostApiRecord = (root = hostRoot()): HostApiRecord => {
  const file = path.join(root, HOST_API_RECORD_FILE);
  if (!statSync(file, { throwIfNoEntry: false })?.isFile()) throw new Error(`${file} is missing; generate it with pnpm update:host-api`);
  return JSON.parse(readFileSync(file, "utf8")) as HostApiRecord;
};

/** The stored names must describe the current list and number; building and loading both read them, so both agree with the constant. */
export const checkedHostApiRecord = (root = hostRoot()): HostApiRecord => {
  const record = readHostApiRecord(root);
  if (record.version !== HOST_API_VERSION) {
    throw new Error(`host-api.json describes host API ${record.version}, the host offers ${HOST_API_VERSION}; pnpm update:host-api`);
  }
  for (const half of ["server", "web"] as const) {
    const listed = [...hostApiModules(half)].sort().join("\n");
    if (Object.keys(record[half]).sort().join("\n") !== listed) {
      throw new Error(`host-api.json names different modules for the ${half} half than apps/server/src/host-api.ts; pnpm update:host-api`);
    }
  }
  return record;
};

export interface HostPackage {
  readonly name: string;
  readonly version: string;
  readonly hostVersion: string;
}

/** The npm package @schlenkr/ragents carries the commit it was built from; a checkout does not have this file. */
export const readHostPackage = (root: string = hostRoot()): HostPackage | undefined => {
  const file = path.join(root, "package.json");
  if (!statSync(file, { throwIfNoEntry: false })?.isFile()) return undefined;
  const parsed = JSON.parse(readFileSync(file, "utf8")) as { name?: unknown; version?: unknown; ragents?: { hostVersion?: unknown } };
  const hostVersion = parsed.ragents?.hostVersion;
  if (hostVersion === undefined) return undefined;
  if (typeof hostVersion !== "string" || !/^[0-9a-f]{40}$/.test(hostVersion)) {
    throw new Error(`${file}: ragents.hostVersion must be a full Git commit, not ${JSON.stringify(hostVersion)}`);
  }
  if (typeof parsed.name !== "string" || typeof parsed.version !== "string") throw new Error(`${file}: name and version are missing`);
  return { name: parsed.name, version: parsed.version, hostVersion };
};

/** The version of the npm package: in the package its own, in the checkout that of the root; one source for both. */
export const readPackageVersion = (root: string = hostRoot()): string => {
  const file = path.join(root, "package.json");
  if (!statSync(file, { throwIfNoEntry: false })?.isFile()) throw new Error(`The package version is unknown: ${file} is missing`);
  const version = (JSON.parse(readFileSync(file, "utf8")) as { version?: unknown }).version;
  if (typeof version !== "string" || !/^\d+\.\d+\.\d+/.test(version)) {
    throw new Error(`${file}: version is the package version and must be x.y.z, not ${JSON.stringify(version)}`);
  }
  return version;
};

const gitDirectoryOf = (root: string): string => {
  const entry = path.join(root, ".git");
  const stats = statSync(entry, { throwIfNoEntry: false });
  if (!stats) throw new Error(`The host version is unknown: ${entry} is missing; the host needs a Git checkout or the package @schlenkr/ragents`);
  if (stats.isDirectory()) return entry;
  const pointer = /^gitdir:\s*(.+)\s*$/.exec(readFileSync(entry, "utf8"));
  if (!pointer) throw new Error(`The host version is unknown: ${entry} names no gitdir`);
  return path.resolve(root, pointer[1]!.trim());
};

const refFrom = (gitDirectory: string, ref: string): string | undefined => {
  const direct = statSync(path.join(gitDirectory, ref), { throwIfNoEntry: false })?.isFile()
    ? readFileSync(path.join(gitDirectory, ref), "utf8").trim() : undefined;
  if (direct) return direct;
  const packed = path.join(gitDirectory, "packed-refs");
  if (!statSync(packed, { throwIfNoEntry: false })?.isFile()) return undefined;
  const line = readFileSync(packed, "utf8").split("\n").find((entry) => entry.endsWith(` ${ref}`));
  return line?.split(" ")[0];
};

/** The commit of the running host: from the package @schlenkr/ragents, otherwise from the Git checkout with worktrees and packed refs. */
export const readHostVersion = (root: string = hostRoot()): string => {
  const packaged = readHostPackage(root);
  if (packaged) return packaged.hostVersion;
  const gitDirectory = gitDirectoryOf(root);
  const head = readFileSync(path.join(gitDirectory, "HEAD"), "utf8").trim();
  const ref = /^ref:\s*(.+)$/.exec(head)?.[1]?.trim();
  if (!ref) {
    if (/^[0-9a-f]{40}$/.test(head)) return head;
    throw new Error(`The host version is unknown: HEAD in ${gitDirectory} is neither a ref nor a commit`);
  }
  const commonDirectory = statSync(path.join(gitDirectory, "commondir"), { throwIfNoEntry: false })?.isFile()
    ? path.resolve(gitDirectory, readFileSync(path.join(gitDirectory, "commondir"), "utf8").trim()) : undefined;
  const commit = refFrom(gitDirectory, ref) ?? (commonDirectory ? refFrom(commonDirectory, ref) : undefined);
  if (!commit || !/^[0-9a-f]{40}$/.test(commit)) throw new Error(`The host version is unknown: ${ref} in ${gitDirectory} points to no commit`);
  return commit;
};
