import { readFileSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { HOST_API_VERSION, hostApiModules } from "./host-api.js";

export const hostRoot = (): string => path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

/** The value names of the host API and its number, relative to the host root; generated by pnpm update:host-api. */
export const HOST_API_RECORD_FILE = "apps/server/src/host-api.json";

/** Die Nummer der Host-API eines Hosts an beliebiger Stelle; so prüft auch die Erweiterung einen Host, der nicht sie selbst ist. */
export const readHostApiVersion = (root: string = hostRoot()): number => {
  const file = path.join(root, HOST_API_RECORD_FILE);
  if (!statSync(file, { throwIfNoEntry: false })?.isFile()) throw new Error(`Die Host-API ist unbekannt: ${file} fehlt`);
  const version = (JSON.parse(readFileSync(file, "utf8")) as { version?: unknown }).version;
  if (typeof version !== "number" || !Number.isInteger(version) || version < 1) throw new Error(`${file}: version ist keine Nummer der Host-API`);
  return version;
};

/** The value names each module of the host API offers at runtime, per half; the build tool generates the web shims from it. */
export interface HostApiRecord {
  readonly version: number;
  readonly server: Readonly<Record<string, readonly string[]>>;
  readonly web: Readonly<Record<string, readonly string[]>>;
}

export const readHostApiRecord = (root = hostRoot()): HostApiRecord => {
  const file = path.join(root, HOST_API_RECORD_FILE);
  if (!statSync(file, { throwIfNoEntry: false })?.isFile()) throw new Error(`${file} fehlt; mit pnpm update:host-api erzeugen`);
  return JSON.parse(readFileSync(file, "utf8")) as HostApiRecord;
};

/** The stored names must describe the current list and number; building and loading both read them, so both agree with the constant. */
export const checkedHostApiRecord = (root = hostRoot()): HostApiRecord => {
  const record = readHostApiRecord(root);
  if (record.version !== HOST_API_VERSION) {
    throw new Error(`host-api.json beschreibt Host-API ${record.version}, der Host bietet ${HOST_API_VERSION}; pnpm update:host-api`);
  }
  for (const half of ["server", "web"] as const) {
    const listed = [...hostApiModules(half)].sort().join("\n");
    if (Object.keys(record[half]).sort().join("\n") !== listed) {
      throw new Error(`host-api.json nennt für die ${half}-Hälfte andere Module als apps/server/src/host-api.ts; pnpm update:host-api`);
    }
  }
  return record;
};

export interface HostPackage {
  readonly name: string;
  readonly version: string;
  readonly hostVersion: string;
}

/** Das npm-Paket @schlenkr/ragents trägt den Commit, aus dem es gebaut wurde; ein Checkout hat diese Datei nicht. */
export const readHostPackage = (root: string = hostRoot()): HostPackage | undefined => {
  const file = path.join(root, "package.json");
  if (!statSync(file, { throwIfNoEntry: false })?.isFile()) return undefined;
  const parsed = JSON.parse(readFileSync(file, "utf8")) as { name?: unknown; version?: unknown; ragents?: { hostVersion?: unknown } };
  const hostVersion = parsed.ragents?.hostVersion;
  if (hostVersion === undefined) return undefined;
  if (typeof hostVersion !== "string" || !/^[0-9a-f]{40}$/.test(hostVersion)) {
    throw new Error(`${file}: ragents.hostVersion muss ein vollständiger Git-Commit sein, nicht ${JSON.stringify(hostVersion)}`);
  }
  if (typeof parsed.name !== "string" || typeof parsed.version !== "string") throw new Error(`${file}: name und version fehlen`);
  return { name: parsed.name, version: parsed.version, hostVersion };
};

/** Die Fassung des npm-Pakets: im Paket seine eigene, im Checkout die der Wurzel; eine Quelle für beide. */
export const readPackageVersion = (root: string = hostRoot()): string => {
  const file = path.join(root, "package.json");
  if (!statSync(file, { throwIfNoEntry: false })?.isFile()) throw new Error(`Die Paketfassung ist unbekannt: ${file} fehlt`);
  const version = (JSON.parse(readFileSync(file, "utf8")) as { version?: unknown }).version;
  if (typeof version !== "string" || !/^\d+\.\d+\.\d+/.test(version)) {
    throw new Error(`${file}: version ist die Fassung des Pakets und muss x.y.z sein, nicht ${JSON.stringify(version)}`);
  }
  return version;
};

const gitDirectoryOf = (root: string): string => {
  const entry = path.join(root, ".git");
  const stats = statSync(entry, { throwIfNoEntry: false });
  if (!stats) throw new Error(`Die Host-Version ist unbekannt: ${entry} fehlt; der Host braucht einen Git-Checkout oder das Paket @schlenkr/ragents`);
  if (stats.isDirectory()) return entry;
  const pointer = /^gitdir:\s*(.+)\s*$/.exec(readFileSync(entry, "utf8"));
  if (!pointer) throw new Error(`Die Host-Version ist unbekannt: ${entry} nennt kein gitdir`);
  return path.resolve(root, pointer[1]!.trim());
};

const refFrom = (gitDirectory: string, ref: string): string | undefined => {
  const direct = statSync(path.join(gitDirectory, ref), { throwIfNoEntry: false })?.isFile()
    ? readFileSync(path.join(gitDirectory, ref), "utf8").trim() : undefined;
  if (direct) return direct;
  const packed = path.join(gitDirectory, "packed-refs");
  if (!statSync(packed, { throwIfNoEntry: false })?.isFile()) return undefined;
  const line = readFileSync(packed, "utf8").split("\n").find((entry) => entry.endsWith(` ${ref}`));
  return line?.split(" ")[0];
};

/** Der Commit des laufenden Hosts: aus dem Paket @schlenkr/ragents, sonst aus dem Git-Checkout mit Worktrees und gepackten Refs. */
export const readHostVersion = (root: string = hostRoot()): string => {
  const packaged = readHostPackage(root);
  if (packaged) return packaged.hostVersion;
  const gitDirectory = gitDirectoryOf(root);
  const head = readFileSync(path.join(gitDirectory, "HEAD"), "utf8").trim();
  const ref = /^ref:\s*(.+)$/.exec(head)?.[1]?.trim();
  if (!ref) {
    if (/^[0-9a-f]{40}$/.test(head)) return head;
    throw new Error(`Die Host-Version ist unbekannt: HEAD in ${gitDirectory} ist weder Ref noch Commit`);
  }
  const commonDirectory = statSync(path.join(gitDirectory, "commondir"), { throwIfNoEntry: false })?.isFile()
    ? path.resolve(gitDirectory, readFileSync(path.join(gitDirectory, "commondir"), "utf8").trim()) : undefined;
  const commit = refFrom(gitDirectory, ref) ?? (commonDirectory ? refFrom(commonDirectory, ref) : undefined);
  if (!commit || !/^[0-9a-f]{40}$/.test(commit)) throw new Error(`Die Host-Version ist unbekannt: ${ref} in ${gitDirectory} zeigt auf keinen Commit`);
  return commit;
};
