import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, mkdir, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "esbuild";
import { chromium, type Locator } from "playwright-core";
import { tailwindPlugin } from "./tailwind-plugin";
import type {} from "./docking-fixture";

const defaultSideWidth = 630;
const contrast = (first: string, second: string) => {
  const luminance = (color: string) => {
    const channels = color.match(/[\d.]+/g)!.slice(0, 3).map((value) => Number(value) / 255);
    const [red, green, blue] = channels.map((channel) => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4);
    return red * 0.2126 + green * 0.7152 + blue * 0.0722;
  };
  const [light, dark] = [luminance(first), luminance(second)].sort((a, b) => b - a);
  return (light + 0.05) / (dark + 0.05);
};
const browserOnly = { skip: process.env.RAGENTS_BROWSER_TESTS !== "1", timeout: 120_000 };

async function fixturePage(context: test.TestContext) {
  const directory = await mkdtemp(join(tmpdir(), "ragents-docking-"));
  context.after(() => rm(directory, { recursive: true, force: true }));
  const root = fileURLToPath(new URL("../../../", import.meta.url));
  await build({ entryPoints: [fileURLToPath(new URL("docking-fixture.tsx", import.meta.url))], bundle: true,
    platform: "browser", format: "iife", jsx: "automatic", outfile: join(directory, "fixture.js"),
    plugins: [tailwindPlugin([`${root}apps/web/src`])], logLevel: "silent" });
  await writeFile(join(directory, "index.html"), '<!doctype html><html><head><link rel="stylesheet" href="fixture.css"></head><body><div id="root" style="height:700px;display:flex"></div><script src="fixture.js"></script></body></html>');
  const browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_EXECUTABLE_PATH ?? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" });
  context.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });
  return { page, url: pathToFileURL(join(directory, "index.html")).href };
}

test("a flyout that a click in the chat opens stays open until a later outside click", browserOnly, async (context) => {
  const { page, url } = await fixturePage(context);
  await page.goto(url);
  const sidebar = page.locator("[data-dock-sidebar]");
  await page.getByRole("button", { name: "Reveal Files from chat", exact: true }).click();
  await sidebar.waitFor();
  await page.waitForTimeout(1000);
  assert.equal(await sidebar.isVisible(), true, "the press that opened the flyout is not an outside click");
  await page.mouse.click(10, 300);
  await sidebar.waitFor({ state: "hidden" });
});

test("a dialog opened from the sidebar flyout keeps the flyout and loads while the pointer rests on it", browserOnly, async (context) => {
  const { page, url } = await fixturePage(context);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(url);
  const rail = page.getByRole("navigation", { name: "Sidebar tabs" });
  const sidebar = page.locator("[data-dock-sidebar]");
  await rail.getByRole("button", { name: "Journal", exact: true }).hover();
  await sidebar.waitFor();
  await page.getByRole("button", { name: "Open details", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Journal details" });
  await dialog.waitFor();
  const bounds = await dialog.boundingBox();
  assert.ok(bounds);
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2, { steps: 4 });
  await page.waitForTimeout(1000);
  assert.equal(await sidebar.isVisible(), true, "an open modal dialog holds the hover flyout open");
  assert.equal(await dialog.getByText("Details loaded", { exact: true }).isVisible(), true, "the dialog's request completes");
  await page.keyboard.press("Escape");
  await dialog.waitFor({ state: "hidden" });
  await page.mouse.click(10, 100);
  await sidebar.waitFor({ state: "hidden" });
  assert.deepEqual(errors, []);
});

test("browser docking preserves frames and drafts through split, merge, close, maximize, rail and catalog changes", browserOnly, async (context) => {
  const { page, url } = await fixturePage(context);
  const shots = join(tmpdir(), "ragents-browser-shots");
  await mkdir(shots, { recursive: true });
  const screenshot = (name: string) => page.screenshot({ path: join(shots, `docking-${name}.png`) });
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(url);
  const tab = (name: string) => page.getByRole("tab", { name, exact: true });
  const groups = page.locator("[data-dock-group]");
  const rail = page.getByRole("navigation", { name: "Sidebar tabs" });
  const sidebar = page.locator("[data-dock-sidebar]");
  const actions = page.getByRole("group", { name: "Layout actions" });
  const view = (name: string) => actions.getByRole("button", { name, exact: true });
  const savedLayout = () => page.evaluate(() => Object.entries(localStorage).find(([key]) => key.startsWith("ragents.docking:"))?.[1]);
  const visibleShadow = (shadow: string) => (shadow.match(/rgba?\([^)]*\)/g) ?? []).some((color) => !/^rgba\(.*,\s*0\)$/.test(color));
  const box = async (locator: Locator) => { const rect = await locator.boundingBox(); assert.ok(rect); return rect; };
  const startDrag = async (source: Locator, target: Locator) => {
    const from = await box(source);
    const to = await box(target);
    await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2);
    await page.mouse.down();
    await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2 + 100, { steps: 6 });
    await page.locator('[data-dock-guide="group-center"]').waitFor();
    await screenshot("compass");
  };
  const dropGuide = async (guide: string) => {
    const target = await box(page.locator(`[data-dock-guide="${guide}"]`));
    await page.mouse.move(target.x + target.width / 2, target.y + target.height / 2);
    await page.locator("[data-dock-preview]").waitFor();
    await page.mouse.up();
    await page.getByLabel("Docking guides", { exact: true }).waitFor({ state: "hidden" });
  };
  await tab("Chat").waitFor();
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 2);
  const defaultChat = await box(groups.filter({ has: tab("Chat") }));
  const defaultApp = await box(groups.filter({ has: tab("Notes") }));
  assert.ok(defaultChat.x < defaultApp.x, "the default places chat to the left of mini-apps");
  assert.ok(Math.abs(defaultChat.width - defaultApp.width) < 1, "chat and mini-apps share the available width equally");
  assert.equal(await page.getByRole("button", { name: "Close area", exact: true }).count(), 0);
  assert.equal(await page.getByRole("button", { name: "Close Chat", exact: true }).count(), 1);
  assert.equal(await page.getByRole("button", { name: "Close Notes", exact: true }).count(), 1);
  assert.equal(await page.getByRole("button", { name: "Maximize area", exact: true }).count(), 2);
  assert.deepEqual(await groups.filter({ has: tab("Notes") }).getByRole("button").evaluateAll((buttons) => buttons.map((button) => button.getAttribute("aria-label"))),
    ["Move Notes", "Maximize area", "Close Notes"], "maximize sits where the close button was, the close button is outermost");
  await page.evaluate(() => { document.getElementById("root")!.style.width = "900px"; });
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  assert.equal(await page.getByRole("button", { name: "Maximize area", exact: true }).count(), 0);
  assert.equal(await groups.first().getByRole("tab").count(), 2, "a narrow container keeps apps beside chat as tabs");
  await page.evaluate(() => { document.getElementById("root")!.style.width = ""; });
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 2);
  await page.evaluate(() => window.dockingFixture.setApps([]));
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  assert.equal(await page.getByRole("button", { name: "Maximize area", exact: true }).count(), 0);
  await page.evaluate(() => window.dockingFixture.setApps(["notes"]));
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 2);
  assert.equal(await page.getByRole("textbox", { name: "Chat draft" }).isVisible(), true, "a late mini-app opens alongside chat");
  await page.evaluate(() => window.dockingFixture.setApps(["notes", "board"]));
  await tab("Board").waitFor();
  assert.equal(await groups.count(), 2);
  assert.equal(await groups.filter({ has: tab("Notes") }).getByRole("tab", { name: "Board", exact: true }).count(), 1);
  await page.getByRole("button", { name: "Close Notes", exact: true }).click();
  await page.setViewportSize({ width: 900, height: 800 });
  await page.waitForFunction(() => document.querySelector("[data-dock-group]")!.getBoundingClientRect().width < 450);
  assert.equal(await groups.count(), 2, "manually changed layouts survive narrower containers");
  assert.equal(await tab("Notes").count(), 0, "responsive layout does not reopen closed tabs");
  await page.getByRole("button", { name: "Reset layout", exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  assert.equal(await tab("Notes").count(), 1, "reset restores all available mini-apps");
  await page.setViewportSize({ width: 1200, height: 800 });
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 2);
  assert.deepEqual(await actions.getByRole("button").evaluateAll((buttons) => buttons.map((button) => [button.getAttribute("aria-label"), button.getAttribute("aria-pressed")])),
    [["Chat", "true"], ["Notes", "true"], ["Board", "false"], ["Empty space", null], ["Reset layout", null]], "every view keeps its button, pressed while visible");
  await view("Board").click();
  assert.equal(await groups.count(), 2, "a background tab is activated in its area");
  assert.equal(await page.getByRole("tabpanel", { name: "Board", exact: true }).isVisible(), true);
  assert.equal(await page.getByRole("tabpanel", { name: "Notes", exact: true }).isVisible(), false);
  assert.equal(await view("Board").getAttribute("aria-pressed"), "true");
  assert.equal(await view("Notes").getAttribute("aria-pressed"), "false");
  const layout = await savedLayout();
  await view("Board").click();
  assert.equal(await savedLayout(), layout, "the button of a visible view changes nothing");
  await page.getByRole("button", { name: "Close Board", exact: true }).click();
  assert.equal(await view("Board").getAttribute("aria-pressed"), "false");
  await view("Board").click();
  assert.equal(await groups.count(), 3, "reopening a closed app creates a split when there is room");
  assert.equal(await page.getByRole("tabpanel", { name: "Chat", exact: true }).isVisible(), true);
  assert.equal(await page.getByRole("tabpanel", { name: "Notes", exact: true }).isVisible(), true);
  assert.equal(await page.getByRole("tabpanel", { name: "Board", exact: true }).isVisible(), true);
  await page.setViewportSize({ width: 400, height: 800 });
  await page.evaluate(() => window.dockingFixture.setApps(["notes", ...Array.from({ length: 30 }, (_, index) => `app${index}`)]));
  await view("App29").waitFor();
  assert.equal(await actions.getByRole("button").count(), 34, "every window and extra/reset action stays direct with many windows");
  assert.equal(await actions.getByRole("button", { name: /^All windows/ }).count(), 0);
  assert.ok(new Set(await actions.getByRole("button").evaluateAll((buttons) => buttons.map((button) => button.getBoundingClientRect().top))).size > 1, "many window buttons wrap");
  await view("Reset layout").click();
  assert.equal(await view("Chat").getAttribute("aria-pressed"), "true");
  await view("App29").click();
  assert.equal(await page.getByRole("tabpanel", { name: "App29", exact: true }).isVisible(), true);
  assert.equal(await groups.count(), 1, "the direct window button selects a tab when space is narrow");
  await page.setViewportSize({ width: 900, height: 800 });
  await page.reload();
  await tab("Chat").waitFor();
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  assert.equal(await page.getByRole("tabpanel", { name: "Chat", exact: true }).getAttribute("aria-labelledby"), await tab("Chat").getAttribute("id"));
  assert.equal(await page.locator("section[aria-label=Chat]").count(), 0, "The dock wrapper does not duplicate its content's region label.");
  await page.getByRole("textbox", { name: "Chat draft" }).fill("Unsent chat");
  const chat = await page.getByRole("textbox", { name: "Chat draft" }).elementHandle();
  const chatWidth = (await box(tab("Chat").locator(".."))).width;
  assert.ok(Math.abs(chatWidth - (await box(tab("Notes").locator(".."))).width) < 1, "tabs share the strip equally");
  await tab("Notes").click();
  await page.getByRole("textbox", { name: "App draft" }).fill("Unsent app");
  await page.frameLocator('iframe[title="App frame"]').getByRole("textbox", { name: "Frame draft" }).fill("Inside frame");
  const frame = await page.locator('iframe[title="App frame"]').elementHandle();
  const frameIdentity = await frame!.evaluate((element) => Reflect.get((element as HTMLIFrameElement).contentWindow!, "identity"));
  await startDrag(tab("Notes"), groups.first());
  await dropGuide("group-right");
  assert.equal(await groups.count(), 2);
  assert.equal(await page.getByRole("textbox", { name: "Chat draft" }).inputValue(), "Unsent chat");
  assert.equal(await page.getByRole("textbox", { name: "App draft" }).inputValue(), "Unsent app");
  assert.equal(await page.locator('iframe[title="App frame"]').evaluate((element, original) => element === original, frame), true);
  assert.equal(await frame!.evaluate((element) => Reflect.get((element as HTMLIFrameElement).contentWindow!, "identity")), frameIdentity);
  const notesGroup = groups.filter({ has: tab("Notes") });
  await notesGroup.getByRole("button", { name: "Maximize area", exact: true }).click();
  assert.equal(await groups.count(), 1);
  assert.equal(await page.getByRole("textbox", { name: "Chat draft" }).isHidden(), true);
  await page.getByRole("button", { name: "Restore area", exact: true }).click();
  assert.equal(await groups.count(), 2);
  await notesGroup.getByRole("button", { name: "Maximize area", exact: true }).click();
  await page.keyboard.press("Escape");
  assert.equal(await groups.count(), 2);
  const divider = page.getByRole("separator", { name: "Resize areas" });
  await divider.focus();
  await page.keyboard.press("ArrowRight");
  assert.equal(await divider.getAttribute("aria-valuenow"), "55");
  assert.equal(await divider.locator("[data-dock-grip] > span").count(), 3);
  const dividerBox = await box(divider);
  assert.ok(dividerBox.width >= 8);
  const beforeResize = await box(notesGroup);
  await page.mouse.move(dividerBox.x + dividerBox.width / 2, dividerBox.y + dividerBox.height / 2);
  await page.mouse.down();
  await page.mouse.move(dividerBox.x + dividerBox.width / 2 + 60, dividerBox.y + dividerBox.height / 2, { steps: 6 });
  assert.equal(await divider.getAttribute("data-dragging"), "true");
  await page.mouse.up();
  assert.ok((await box(notesGroup)).width < beforeResize.width - 50);
  assert.equal(await divider.getAttribute("data-dragging"), "false");
  const cards = await page.locator("[data-dock-card]").all();
  const firstCard = await box(cards[0]);
  const secondCard = await box(cards[1]);
  assert.ok(Math.abs(secondCard.x - firstCard.x - firstCard.width - 6) < 1);
  await startDrag(notesGroup.getByRole("button", { name: "Move Notes", exact: true }), groups.filter({ has: tab("Chat") }));
  await dropGuide("group-center");
  assert.equal(await groups.count(), 1);
  await startDrag(tab("Notes"), groups.first());
  await page.keyboard.press("Escape");
  await page.mouse.up();
  assert.equal(await groups.count(), 1);
  assert.equal(await page.locator("[data-dock-guide]").count(), 0);
  await startDrag(tab("Notes"), groups.first());
  await dropGuide("edge-bottom");
  assert.equal(await groups.count(), 2);
  assert.equal(await page.getByRole("separator", { name: "Resize areas" }).getAttribute("aria-valuenow"), "65");
  const horizontalDivider = page.getByRole("separator", { name: "Resize areas" });
  assert.equal(await horizontalDivider.getAttribute("aria-orientation"), "horizontal");
  assert.equal(await horizontalDivider.locator("[data-dock-grip] > span").count(), 3);
  assert.ok((await box(horizontalDivider)).height >= 8);
  await page.getByRole("button", { name: "Close Notes", exact: true }).click();
  assert.equal(await groups.count(), 1);
  await view("Notes").click();
  assert.equal(await page.frameLocator('iframe[title="App frame"]').getByRole("textbox", { name: "Frame draft" }).inputValue(), "Inside frame");
  assert.equal(await page.evaluate(() => window.dockingFixture.mounts.notes), 1);

  await rail.getByRole("button", { name: "Files", exact: true }).hover();
  const railTooltip = page.locator('[data-slot="tooltip-content"]').filter({ hasText: /^Files$/ });
  await railTooltip.waitFor({ timeout: 300 });
  assert.equal(await rail.getByRole("button", { name: "Files", exact: true }).getAttribute("title"), null);
  await sidebar.waitFor();
  assert.equal(Math.round((await box(page.locator("[data-dock-frame]"))).width), defaultSideWidth);
  const cornerRadius = await page.evaluate(() => `${parseFloat(getComputedStyle(document.documentElement).fontSize) / 2}px`);
  for (const theme of ["light", "dark"]) {
    await page.evaluate((value) => document.documentElement.setAttribute("data-theme", value), theme);
    const tooltip = await railTooltip.evaluate(async (element) => {
      await Promise.allSettled(element.getAnimations().map((animation) => animation.finished));
      const bounds = element.getBoundingClientRect();
      const pointerEvents = getComputedStyle(element).pointerEvents;
      const previous = element.style.pointerEvents;
      element.style.pointerEvents = "auto";
      const uncovered = element.contains(document.elementFromPoint(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2));
      element.style.pointerEvents = previous;
      return { bounds: bounds.toJSON(), side: element.getAttribute("data-side"), pointerEvents, uncovered };
    });
    const buttonBox = await box(rail.getByRole("button", { name: "Files", exact: true }));
    assert.equal(tooltip.side, "left");
    assert.ok(Math.abs(buttonBox.x - tooltip.bounds.right - 8) < 1, "the tooltip appears 8px to the left of the rail button");
    assert.ok(Math.abs(tooltip.bounds.y + tooltip.bounds.height / 2 - buttonBox.y - buttonBox.height / 2) < 2, "the tooltip is vertically centered on the rail button");
    assert.equal(tooltip.pointerEvents, "none", "the tooltip leaves sidebar controls reachable");
    assert.equal(tooltip.uncovered, true, `the tooltip is above the open flyout in the ${theme} theme`);
    for (const card of [page.locator("[data-dock-card]").first(), rail, page.locator("[data-dock-frame]")]) {
      const style = await card.evaluate((element) => {
        const computed = getComputedStyle(element);
        return { border: computed.borderLeftWidth, radius: computed.borderTopLeftRadius };
      });
      assert.equal(style.border, "1px");
      assert.equal(style.radius, cornerRadius, "rounded corners follow the root font size");
    }
    const frameStyle = await page.locator("[data-dock-frame]").evaluate((element) => {
      const style = getComputedStyle(element);
      return { shadow: style.boxShadow, radius: style.borderTopLeftRadius, background: style.backgroundColor };
    });
    assert.ok(visibleShadow(frameStyle.shadow), `the hover flyout casts a shadow in the ${theme} theme`);
    assert.notEqual(frameStyle.radius, "0px");
    assert.notEqual(frameStyle.background, "rgba(0, 0, 0, 0)");
  }
  await page.mouse.move(10, 100);
  await sidebar.waitFor({ state: "hidden" });
  assert.equal(await page.getByRole("separator", { name: "Resize sidebar", exact: true }).count(), 0);
  {
    await rail.getByRole("button", { name: "Files", exact: true }).hover();
    await sidebar.waitFor();
    const handle = page.getByRole("button", { name: "Move sidebar window", exact: true });
    const rect = await box(handle);
    await page.mouse.move(rect.x + rect.width / 2, rect.y + 12);
    await page.mouse.down();
    await page.waitForTimeout(400);
    assert.equal(await sidebar.isVisible(), true, "a pressed grip holds the hover flyout open");
    await page.mouse.up();
    await page.waitForTimeout(400);
    assert.equal(await sidebar.isVisible(), true, "a plain grip press stays open while the pointer remains on it");
    assert.equal(await sidebar.getAttribute("data-dock-sidebar"), "flyout");
    await page.getByRole("button", { name: "Close sidebar", exact: true }).click();
    await page.mouse.move(10, 100);
  }
  await page.getByRole("button", { name: "Reset layout", exact: true }).click();
  await tab("Notes").click();
  const beforeFlyout = (await box(page.locator('[data-dock-panel="app:notes"]'))).width;
  await rail.getByRole("button", { name: "Files", exact: true }).click();
  const filesButton = rail.getByRole("button", { name: "Files", exact: true });
  assert.equal(await filesButton.evaluate((element) => element.matches(":focus")), true, "pointer selection retains native focus");
  assert.equal(await filesButton.evaluate((element) => element.matches(":focus-visible")), false, "pointer selection does not show keyboard focus");
  const pressedRail = await filesButton.evaluate((element) => ({ border: getComputedStyle(element).borderWidth, fill: getComputedStyle(element).backgroundColor,
    rail: getComputedStyle(element.closest("[data-dock-rail]")!).backgroundColor }));
  assert.equal(pressedRail.border, "0px", "a pressed rail button has the shared icon-only look without a border");
  assert.ok(contrast(pressedRail.fill, pressedRail.rail) >= 1.15, `a pressed rail button's fill stands out from the rail (${pressedRail.fill} on ${pressedRail.rail})`);
  assert.equal(visibleShadow(await filesButton.evaluate((element) => getComputedStyle(element).boxShadow)), false, "rail selection stays flat");
  assert.equal(await sidebar.getAttribute("data-dock-sidebar"), "flyout");
  assert.equal(await groups.count(), 1, "a rail click keeps the panel in the overlay");
  const moveIntoLayout = page.getByRole("button", { name: "Move into layout", exact: true });
  assert.equal(await moveIntoLayout.getAttribute("title"), "Move into layout");
  assert.equal(await moveIntoLayout.getAttribute("aria-pressed"), null);
  await page.getByRole("textbox", { name: "Files draft" }).fill("File selection");
  assert.equal((await box(page.locator('[data-dock-panel="app:notes"]'))).width, beforeFlyout, "the flyout does not reserve layout space");
  await moveIntoLayout.click();
  await tab("Files").waitFor();
  assert.equal(await sidebar.count(), 0);
  assert.equal(await groups.count(), 2, "Move into layout opens a regular window");
  const filesGroup = groups.filter({ has: tab("Files") });
  assert.ok((await box(filesGroup)).x > (await box(groups.filter({ has: tab("Notes") }))).x, "the button places the window at the right edge");
  assert.deepEqual(await filesGroup.getByRole("button").evaluateAll((buttons) => buttons.map((button) => button.getAttribute("aria-label"))),
    ["Move Files", "Return Files to sidebar", "Maximize area", "Close Files"]);
  assert.equal(await page.getByRole("separator", { name: "Resize areas", exact: true }).count(), 1);
  await screenshot("moved-into-layout");
  await page.getByRole("button", { name: "Close Files", exact: true }).click();
  assert.equal(await groups.count(), 1);
  assert.equal(await filesButton.count(), 1, "closing the window keeps its rail button");
  assert.equal((await box(page.locator('[data-dock-panel="app:notes"]'))).width, beforeFlyout);
  await filesButton.hover();
  await sidebar.waitFor();
  assert.equal(await page.getByRole("textbox", { name: "Files draft" }).inputValue(), "File selection");
  await rail.getByRole("button", { name: "Journal", exact: true }).click();
  await page.getByText("Journal active", { exact: true }).waitFor();
  assert.equal(await groups.count(), 1);
  assert.equal(Math.round((await box(page.locator("[data-dock-frame]"))).width), defaultSideWidth);
  await page.getByRole("button", { name: "Close sidebar", exact: true }).click();
  assert.equal((await box(page.locator('[data-dock-panel="app:notes"]'))).width, beforeFlyout);
  await sidebar.waitFor({ state: "hidden" });
  await rail.getByRole("button", { name: "Journal", exact: true }).hover();
  await sidebar.waitFor();
  await screenshot("hover");
  await startDrag(page.getByRole("button", { name: "Move sidebar window", exact: true }), groups.first());
  await dropGuide("group-left");
  await screenshot("split-left");
  assert.equal(await rail.getByRole("button", { name: "Journal", exact: true }).count(), 1, "docking a panel preserves its button placement");
  assert.equal(await groups.count(), 2);
  await page.getByRole("button", { name: "Return Journal to sidebar", exact: true }).click();
  await rail.getByRole("button", { name: "Journal", exact: true }).waitFor();
  assert.equal(await groups.count(), 1);
  assert.equal(await sidebar.getAttribute("data-dock-sidebar"), "flyout", "Return to sidebar opens a focused preview");
  assert.equal(await page.getByText("Journal active", { exact: true }).isVisible(), true);
  await startDrag(rail.getByRole("button", { name: "Files", exact: true }), groups.first());
  await dropGuide("group-center");
  assert.equal(await page.getByRole("textbox", { name: "Files draft" }).inputValue(), "File selection");
  await startDrag(tab("Files"), groups.first());
  const railBox = await box(rail);
  await page.mouse.move(railBox.x + railBox.width / 2, railBox.y + 200);
  await page.mouse.up();
  await rail.getByRole("button", { name: "Files", exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Close area", exact: true }).count(), 0);
  await page.getByRole("button", { name: "Close Notes", exact: true }).click();
  await page.getByRole("button", { name: "Close Chat", exact: true }).click();
  await page.getByText("Drop a window here", { exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Close area", exact: true }).count(), 0, "the final empty area stays available");
  assert.equal(await page.getByRole("button", { name: "Maximize area", exact: true }).count(), 0);
  await view("Chat").click();
  assert.equal(await page.getByRole("textbox", { name: "Chat draft" }).evaluate((element, original) => element === original, chat), true);
  await startDrag(tab("Chat"), groups.first());
  await dropGuide("group-left");
  assert.equal(await groups.count(), 2);
  await screenshot("tab-split-left");
  await page.getByText("Drop a window here", { exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Close area", exact: true }).count(), 1, "only the redundant empty area has an area close button");
  assert.equal(await page.getByRole("button", { name: "Maximize area", exact: true }).count(), 1);
  await page.reload();
  await page.getByText("Drop a window here", { exact: true }).waitFor();
  assert.equal(await groups.count(), 2, "the split and closed apps survive reload");
  assert.equal(await tab("Notes").count(), 0);
  await page.evaluate(() => window.dockingFixture.setApps(["notes", "board"]));
  await tab("Board").waitFor();
  assert.equal(await tab("Chat").getAttribute("aria-selected"), "true");
  const boardArea = await box(groups.filter({ has: tab("Board") }));
  await page.evaluate(() => window.dockingFixture.setApps([]));
  await tab("Board").waitFor({ state: "hidden" });
  assert.equal(await groups.count(), 1, "the area of a missing app gives its space away");
  await page.evaluate(() => window.dockingFixture.setApps(["notes", "board"]));
  await tab("Board").waitFor();
  assert.deepEqual(await box(groups.filter({ has: tab("Board") })), boardArea, "a returning app takes its own area again");
  assert.equal(await groups.filter({ has: tab("Chat") }).getByRole("tab", { name: "Board", exact: true }).count(), 0, "it does not join Chat's area");
  await page.evaluate(() => window.dockingFixture.setApps([]));
  await tab("Board").waitFor({ state: "hidden" });
  await page.evaluate(() => window.dockingFixture.setRun("second"));
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  await page.evaluate(() => window.dockingFixture.setRun("first"));
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  await page.getByRole("button", { name: "Reset layout", exact: true }).click();
  assert.equal(await groups.count(), 1);
  await page.evaluate(() => document.documentElement.setAttribute("data-theme", "dark"));
  assert.equal(await tab("Chat").isVisible(), true);
  await rail.getByRole("button", { name: "Files", exact: true }).click();
  await page.getByRole("button", { name: "Move into layout", exact: true }).click();
  await tab("Files").waitFor();
  await page.reload();
  await tab("Files").waitFor();
  assert.equal(await groups.count(), 2, "the regular tool window survives reload");
  assert.equal(await sidebar.count(), 0);
  await rail.getByRole("button", { name: "Files", exact: true }).click();
  assert.equal(await sidebar.count(), 0, "a docked tool's rail button selects its window");
  await page.getByRole("button", { name: "Close Files", exact: true }).click();
  await page.mouse.move(10, 100);
  await rail.getByRole("button", { name: "Files", exact: true }).hover();
  await sidebar.waitFor();
  await page.getByRole("textbox", { name: "Files draft" }).click();
  await page.mouse.move(10, 100);
  await sidebar.waitFor({ state: "hidden" });
  await rail.getByRole("button", { name: "Files", exact: true }).hover();
  await sidebar.waitFor();
  const savedSides = await page.evaluate(() => Object.entries(localStorage)
    .filter(([key]) => key.startsWith("ragents.docking:"))
    .map(([, value]) => JSON.parse(value).side));
  assert.ok(savedSides.length > 0);
  assert.ok(savedSides.every((side) => side.mode === "hidden"), "hover previews are never persisted");
  assert.ok(savedSides.every((side) => !Object.hasOwn(side, "width")), "sidebar width is not stored");
  await page.mouse.move(10, 100);
  await page.reload();
  await tab("Chat").waitFor();
  assert.equal(await sidebar.count(), 0, "hover previews do not survive reload");
  assert.deepEqual(errors, []);
});
