import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, mkdir, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "esbuild";
import { chromium, type Locator } from "playwright-core";
import { tailwindPlugin } from "./tailwind-plugin";
import type {} from "./docking-fixture";

const defaultSideWidth = 630;

test("browser docking preserves frames and drafts through split, merge, close, maximize, rail and catalog changes", {
  skip: process.env.RAGENTS_BROWSER_TESTS !== "1", timeout: 120_000,
}, async (context) => {
  const directory = await mkdtemp(join(tmpdir(), "ragents-docking-"));
  context.after(() => rm(directory, { recursive: true, force: true }));
  const root = fileURLToPath(new URL("../../../", import.meta.url));
  await build({ entryPoints: [fileURLToPath(new URL("docking-fixture.tsx", import.meta.url))], bundle: true,
    platform: "browser", format: "iife", jsx: "automatic", outfile: join(directory, "fixture.js"),
    plugins: [tailwindPlugin([`${root}apps/web/src`])], logLevel: "silent" });
  await writeFile(join(directory, "index.html"), '<!doctype html><html><head><link rel="stylesheet" href="fixture.css"></head><body><div id="root" style="height:700px;display:flex"></div><script src="fixture.js"></script></body></html>');
  const browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_EXECUTABLE_PATH ?? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" });
  context.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });
  const shots = join(tmpdir(), "ragents-browser-shots");
  await mkdir(shots, { recursive: true });
  const screenshot = (name: string) => page.screenshot({ path: join(shots, `docking-${name}.png`) });
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(pathToFileURL(join(directory, "index.html")).href);
  const tab = (name: string) => page.getByRole("tab", { name, exact: true });
  const groups = page.locator("[data-dock-group]");
  const rail = page.getByRole("navigation", { name: "Sidebar tabs" });
  const sidebar = page.locator("[data-dock-sidebar]");
  const actions = page.getByRole("group", { name: "Layout actions" });
  const view = (name: string) => actions.getByRole("button", { name, exact: true });
  const savedLayout = () => page.evaluate(() => Object.entries(localStorage).find(([key]) => key.startsWith("ragents.docking:"))?.[1]);
  const visibleShadow = (shadow: string) => (shadow.match(/rgba?\([^)]*\)/g) ?? []).some((color) => !/^rgba\(.*,\s*0\)$/.test(color));
  const box = async (locator: Locator) => { const rect = await locator.boundingBox(); assert.ok(rect); return rect; };
  const startDrag = async (source: Locator, target: Locator) => {
    const from = await box(source);
    const to = await box(target);
    await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2);
    await page.mouse.down();
    await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2 + 100, { steps: 6 });
    await page.locator('[data-dock-guide="group-center"]').waitFor();
    await screenshot("compass");
  };
  const dropGuide = async (guide: string) => {
    const target = await box(page.locator(`[data-dock-guide="${guide}"]`));
    await page.mouse.move(target.x + target.width / 2, target.y + target.height / 2);
    await page.locator("[data-dock-preview]").waitFor();
    await page.mouse.up();
    await page.getByLabel("Docking guides", { exact: true }).waitFor({ state: "hidden" });
  };
  await tab("Chat").waitFor();
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 2);
  const defaultChat = await box(groups.filter({ has: tab("Chat") }));
  const defaultApp = await box(groups.filter({ has: tab("Notes") }));
  assert.ok(defaultChat.x < defaultApp.x, "the default places chat to the left of mini-apps");
  assert.ok(Math.abs(defaultChat.width - defaultApp.width) < 1, "chat and mini-apps share the available width equally");
  assert.equal(await page.getByRole("button", { name: "Close area", exact: true }).count(), 0);
  assert.equal(await page.getByRole("button", { name: "Close Chat", exact: true }).count(), 1);
  assert.equal(await page.getByRole("button", { name: "Close Notes", exact: true }).count(), 1);
  assert.equal(await page.getByRole("button", { name: "Maximize area", exact: true }).count(), 2);
  assert.deepEqual(await groups.filter({ has: tab("Notes") }).getByRole("button").evaluateAll((buttons) => buttons.map((button) => button.getAttribute("aria-label"))),
    ["Move area", "Maximize area", "Close Notes"], "maximize sits where the close button was, the close button is outermost");
  await page.evaluate(() => { document.getElementById("root")!.style.width = "900px"; });
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  assert.equal(await page.getByRole("button", { name: "Maximize area", exact: true }).count(), 0);
  assert.equal(await groups.first().getByRole("tab").count(), 2, "a narrow container keeps apps beside chat as tabs");
  await page.evaluate(() => { document.getElementById("root")!.style.width = ""; });
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 2);
  await page.evaluate(() => window.dockingFixture.setApps([]));
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  assert.equal(await page.getByRole("button", { name: "Maximize area", exact: true }).count(), 0);
  await page.evaluate(() => window.dockingFixture.setApps(["notes"]));
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 2);
  assert.equal(await page.getByRole("textbox", { name: "Chat draft" }).isVisible(), true, "a late mini-app opens alongside chat");
  await page.evaluate(() => window.dockingFixture.setApps(["notes", "board"]));
  await tab("Board").waitFor();
  assert.equal(await groups.count(), 2);
  assert.equal(await groups.filter({ has: tab("Notes") }).getByRole("tab", { name: "Board", exact: true }).count(), 1);
  await page.getByRole("button", { name: "Close Notes", exact: true }).click();
  await page.setViewportSize({ width: 900, height: 800 });
  await page.waitForFunction(() => document.querySelector("[data-dock-group]")!.getBoundingClientRect().width < 450);
  assert.equal(await groups.count(), 2, "manually changed layouts survive narrower containers");
  assert.equal(await tab("Notes").count(), 0, "responsive layout does not reopen closed tabs");
  await page.getByRole("button", { name: "Reset layout", exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  assert.equal(await tab("Notes").count(), 1, "reset restores all available mini-apps");
  await page.setViewportSize({ width: 1200, height: 800 });
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 2);
  assert.deepEqual(await actions.getByRole("button").evaluateAll((buttons) => buttons.map((button) => [button.getAttribute("aria-label"), button.getAttribute("aria-pressed")])),
    [["Chat", "true"], ["Notes", "true"], ["Board", "false"], ["Empty space", null], ["Reset layout", null]], "every view keeps its button, pressed while visible");
  await view("Board").click();
  assert.equal(await groups.count(), 2, "a background tab is activated in its area");
  assert.equal(await page.getByRole("tabpanel", { name: "Board", exact: true }).isVisible(), true);
  assert.equal(await page.getByRole("tabpanel", { name: "Notes", exact: true }).isVisible(), false);
  assert.equal(await view("Board").getAttribute("aria-pressed"), "true");
  assert.equal(await view("Notes").getAttribute("aria-pressed"), "false");
  const layout = await savedLayout();
  await view("Board").click();
  assert.equal(await savedLayout(), layout, "the button of a visible view changes nothing");
  await page.getByRole("button", { name: "Close Board", exact: true }).click();
  assert.equal(await view("Board").getAttribute("aria-pressed"), "false");
  await view("Board").click();
  assert.equal(await groups.count(), 3, "reopening a closed app creates a split when there is room");
  assert.equal(await page.getByRole("tabpanel", { name: "Chat", exact: true }).isVisible(), true);
  assert.equal(await page.getByRole("tabpanel", { name: "Notes", exact: true }).isVisible(), true);
  assert.equal(await page.getByRole("tabpanel", { name: "Board", exact: true }).isVisible(), true);
  await page.setViewportSize({ width: 400, height: 800 });
  await page.evaluate(() => window.dockingFixture.setApps(["notes", ...Array.from({ length: 30 }, (_, index) => `app${index}`)]));
  const allWindows = actions.getByRole("button", { name: /^All windows/ });
  await allWindows.waitFor();
  assert.equal(await view("Reset layout").count(), 0, "more than five windows move every entry into one menu");
  await allWindows.click();
  await page.getByRole("menuitem", { name: "Reset layout", exact: true }).click();
  await allWindows.click();
  assert.equal(await page.getByRole("menuitemcheckbox", { name: "Chat", exact: true }).getAttribute("aria-checked"), "true");
  await page.getByRole("menuitemcheckbox", { name: "App29", exact: true }).click();
  assert.equal(await page.getByRole("tabpanel", { name: "App29", exact: true }).isVisible(), true);
  assert.equal(await groups.count(), 1, "the overflow menu selects a tab when space is narrow");
  await page.setViewportSize({ width: 900, height: 800 });
  await page.reload();
  await tab("Chat").waitFor();
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  assert.equal(await page.getByRole("tabpanel", { name: "Chat", exact: true }).getAttribute("aria-labelledby"), await tab("Chat").getAttribute("id"));
  assert.equal(await page.locator("section[aria-label=Chat]").count(), 0, "The dock wrapper does not duplicate its content's region label.");
  await page.getByRole("textbox", { name: "Chat draft" }).fill("Unsent chat");
  const chat = await page.getByRole("textbox", { name: "Chat draft" }).elementHandle();
  const chatWidth = (await box(tab("Chat"))).width;
  assert.ok(Math.abs(chatWidth - (await box(tab("Notes"))).width) < 1, "tabs share the strip equally");
  await tab("Notes").click();
  await page.getByRole("textbox", { name: "App draft" }).fill("Unsent app");
  await page.frameLocator('iframe[title="App frame"]').getByRole("textbox", { name: "Frame draft" }).fill("Inside frame");
  const frame = await page.locator('iframe[title="App frame"]').elementHandle();
  const frameIdentity = await frame!.evaluate((element) => Reflect.get((element as HTMLIFrameElement).contentWindow!, "identity"));
  await startDrag(tab("Notes"), groups.first());
  await dropGuide("group-right");
  assert.equal(await groups.count(), 2);
  assert.equal(await page.getByRole("textbox", { name: "Chat draft" }).inputValue(), "Unsent chat");
  assert.equal(await page.getByRole("textbox", { name: "App draft" }).inputValue(), "Unsent app");
  assert.equal(await page.locator('iframe[title="App frame"]').evaluate((element, original) => element === original, frame), true);
  assert.equal(await frame!.evaluate((element) => Reflect.get((element as HTMLIFrameElement).contentWindow!, "identity")), frameIdentity);
  const notesGroup = groups.filter({ has: tab("Notes") });
  await notesGroup.getByRole("button", { name: "Maximize area", exact: true }).click();
  assert.equal(await groups.count(), 1);
  assert.equal(await page.getByRole("textbox", { name: "Chat draft" }).isHidden(), true);
  await page.getByRole("button", { name: "Restore area", exact: true }).click();
  assert.equal(await groups.count(), 2);
  await notesGroup.getByRole("button", { name: "Maximize area", exact: true }).click();
  await page.keyboard.press("Escape");
  assert.equal(await groups.count(), 2);
  const divider = page.getByRole("separator", { name: "Resize areas" });
  await divider.focus();
  await page.keyboard.press("ArrowRight");
  assert.equal(await divider.getAttribute("aria-valuenow"), "55");
  assert.equal(await divider.locator("[data-dock-grip] > span").count(), 3);
  const dividerBox = await box(divider);
  assert.ok(dividerBox.width >= 8);
  const beforeResize = await box(notesGroup);
  await page.mouse.move(dividerBox.x + dividerBox.width / 2, dividerBox.y + dividerBox.height / 2);
  await page.mouse.down();
  await page.mouse.move(dividerBox.x + dividerBox.width / 2 + 60, dividerBox.y + dividerBox.height / 2, { steps: 6 });
  assert.equal(await divider.getAttribute("data-dragging"), "true");
  await page.mouse.up();
  assert.ok((await box(notesGroup)).width < beforeResize.width - 50);
  assert.equal(await divider.getAttribute("data-dragging"), "false");
  const cards = await page.locator("[data-dock-card]").all();
  const firstCard = await box(cards[0]);
  const secondCard = await box(cards[1]);
  assert.ok(Math.abs(secondCard.x - firstCard.x - firstCard.width - 6) < 1);
  await startDrag(notesGroup.getByRole("button", { name: "Move area", exact: true }), groups.filter({ has: tab("Chat") }));
  await dropGuide("group-center");
  assert.equal(await groups.count(), 1);
  await startDrag(tab("Notes"), groups.first());
  await page.keyboard.press("Escape");
  await page.mouse.up();
  assert.equal(await groups.count(), 1);
  assert.equal(await page.locator("[data-dock-guide]").count(), 0);
  await startDrag(tab("Notes"), groups.first());
  await dropGuide("edge-bottom");
  assert.equal(await groups.count(), 2);
  assert.equal(await page.getByRole("separator", { name: "Resize areas" }).getAttribute("aria-valuenow"), "65");
  const horizontalDivider = page.getByRole("separator", { name: "Resize areas" });
  assert.equal(await horizontalDivider.getAttribute("aria-orientation"), "horizontal");
  assert.equal(await horizontalDivider.locator("[data-dock-grip] > span").count(), 3);
  assert.ok((await box(horizontalDivider)).height >= 8);
  await page.getByRole("button", { name: "Close Notes", exact: true }).click();
  assert.equal(await groups.count(), 1);
  await view("Notes").click();
  assert.equal(await page.frameLocator('iframe[title="App frame"]').getByRole("textbox", { name: "Frame draft" }).inputValue(), "Inside frame");
  assert.equal(await page.evaluate(() => window.dockingFixture.mounts.notes), 1);

  await rail.getByRole("button", { name: "Files", exact: true }).hover();
  const railTooltip = page.locator('[data-slot="tooltip-content"]').filter({ hasText: /^Files$/ });
  await railTooltip.waitFor({ timeout: 300 });
  assert.equal(await rail.getByRole("button", { name: "Files", exact: true }).getAttribute("title"), null);
  const tooltipBox = await box(railTooltip);
  const buttonBox = await box(rail.getByRole("button", { name: "Files", exact: true }));
  assert.ok(tooltipBox.x + tooltipBox.width <= buttonBox.x, "the tooltip appears to the left of the rail button");
  assert.ok(Math.abs(tooltipBox.y + tooltipBox.height / 2 - buttonBox.y - buttonBox.height / 2) < 2, "the tooltip is vertically centered on the rail button");
  await sidebar.waitFor();
  assert.equal(Math.round((await box(page.locator("[data-dock-frame]"))).width), defaultSideWidth);
  for (const theme of ["light", "dark"]) {
    await page.evaluate((value) => document.documentElement.setAttribute("data-theme", value), theme);
    for (const card of [page.locator("[data-dock-card]").first(), rail, page.locator("[data-dock-frame]")]) {
      const style = await card.evaluate((element) => {
        const computed = getComputedStyle(element);
        return { border: computed.borderLeftWidth, radius: computed.borderTopLeftRadius };
      });
      assert.equal(style.border, "1px");
      assert.equal(style.radius, "8px");
    }
    const frameStyle = await page.locator("[data-dock-frame]").evaluate((element) => {
      const style = getComputedStyle(element);
      return { shadow: style.boxShadow, radius: style.borderTopLeftRadius, background: style.backgroundColor };
    });
    assert.ok(visibleShadow(frameStyle.shadow), `the hover flyout casts a shadow in the ${theme} theme`);
    assert.notEqual(frameStyle.radius, "0px");
    assert.notEqual(frameStyle.background, "rgba(0, 0, 0, 0)");
  }
  await page.mouse.move(10, 100);
  await sidebar.waitFor({ state: "hidden" });
  for (const grip of ["Resize sidebar", "Move sidebar window"]) {
    await rail.getByRole("button", { name: "Files", exact: true }).hover();
    await sidebar.waitFor();
    const handle = page.getByRole(grip === "Resize sidebar" ? "separator" : "button", { name: grip, exact: true });
    const rect = await box(handle);
    await page.mouse.move(rect.x + rect.width / 2, rect.y + 12);
    await page.mouse.down();
    await page.waitForTimeout(400);
    assert.equal(await sidebar.isVisible(), true, "a pressed grip holds the hover flyout open");
    await page.mouse.up();
    await page.waitForTimeout(400);
    assert.equal(await sidebar.isVisible(), true, "a plain grip press stays open while the pointer remains on it");
    assert.equal(await sidebar.getAttribute("data-dock-sidebar"), "flyout");
    await page.getByRole("button", { name: "Close sidebar", exact: true }).click();
    await page.mouse.move(10, 100);
  }
  await rail.getByRole("button", { name: "Files", exact: true }).hover();
  const resize = await box(page.getByRole("separator", { name: "Resize sidebar" }));
  await page.mouse.move(resize.x + resize.width / 2, resize.y + 100);
  await page.mouse.down();
  await page.mouse.move(resize.x - 70, resize.y + 100, { steps: 6 });
  await page.waitForTimeout(400);
  await page.mouse.up();
  await page.waitForTimeout(400);
  assert.equal(await sidebar.isVisible(), true);
  const resizedWidth = (await box(page.locator("[data-dock-frame]"))).width;
  assert.ok(resizedWidth > defaultSideWidth + 60);
  assert.equal(await sidebar.getAttribute("data-dock-sidebar"), "flyout");
  const savedWidth = await page.evaluate(() => JSON.parse(Object.entries(localStorage).find(([key]) => key.startsWith("ragents.docking:"))![1]).side.width);
  assert.equal(savedWidth, resizedWidth);
  await page.getByRole("button", { name: "Close sidebar", exact: true }).click();
  await page.getByRole("button", { name: "Reset layout", exact: true }).click();
  await tab("Notes").click();
  const beforePin = (await box(page.locator('[data-dock-panel="app:notes"]'))).width;
  await rail.getByRole("button", { name: "Files", exact: true }).click();
  const filesButton = rail.getByRole("button", { name: "Files", exact: true });
  assert.equal(await filesButton.evaluate((element) => element.matches(":focus")), true, "pointer selection retains native focus");
  assert.equal(await filesButton.evaluate((element) => element.matches(":focus-visible")), false, "pointer selection does not show keyboard focus");
  assert.equal(await filesButton.evaluate((element) => getComputedStyle(element).borderWidth), "1px", "selected rail navigation has a uniform one-pixel border");
  assert.equal(visibleShadow(await filesButton.evaluate((element) => getComputedStyle(element).boxShadow)), false, "rail selection stays flat");
  await page.mouse.move(10, 100);
  await page.waitForTimeout(400);
  assert.equal(await sidebar.getAttribute("data-dock-sidebar"), "docked");
  assert.equal(await page.getByRole("button", { name: "Unpin sidebar", exact: true }).getAttribute("aria-pressed"), "true");
  await screenshot("docked");
  await page.getByRole("textbox", { name: "Files draft" }).fill("File selection");
  assert.ok((await box(page.locator('[data-dock-panel="app:notes"]'))).width < beforePin - 200);
  assert.equal(visibleShadow(await page.locator("[data-dock-frame]").evaluate((element) => getComputedStyle(element).boxShadow)), false, "the pinned sidebar has no shadow");
  await rail.getByRole("button", { name: "Journal", exact: true }).click();
  await page.getByText("Journal active", { exact: true }).waitFor();
  assert.equal(await groups.count(), 1);
  assert.equal(Math.round((await box(page.locator("[data-dock-frame]"))).width), defaultSideWidth, "Reset layout restores the default sidebar width");
  await page.getByRole("separator", { name: "Resize sidebar" }).focus();
  await page.keyboard.press("ArrowLeft");
  assert.equal(Math.round((await box(page.locator("[data-dock-frame]"))).width), defaultSideWidth + 20, "ArrowLeft widens the pinned sidebar by one step");
  await page.getByRole("button", { name: "Unpin sidebar", exact: true }).click();
  assert.equal((await box(page.locator('[data-dock-panel="app:notes"]'))).width, beforePin);
  await sidebar.waitFor({ state: "hidden" });
  await rail.getByRole("button", { name: "Journal", exact: true }).hover();
  await sidebar.waitFor();
  await screenshot("hover");
  await startDrag(page.getByRole("button", { name: "Move sidebar window", exact: true }), groups.first());
  await dropGuide("group-left");
  await screenshot("split-left");
  assert.equal(await rail.getByRole("button", { name: "Journal", exact: true }).count(), 0);
  assert.equal(await groups.count(), 2);
  await page.getByRole("button", { name: "Return Journal to sidebar", exact: true }).click();
  await rail.getByRole("button", { name: "Journal", exact: true }).waitFor();
  assert.equal(await groups.count(), 1);
  await startDrag(rail.getByRole("button", { name: "Files", exact: true }), groups.first());
  await dropGuide("group-center");
  assert.equal(await page.getByRole("textbox", { name: "Files draft" }).inputValue(), "File selection");
  await startDrag(tab("Files"), groups.first());
  const railBox = await box(rail);
  await page.mouse.move(railBox.x + railBox.width / 2, railBox.y + 200);
  await page.mouse.up();
  await rail.getByRole("button", { name: "Files", exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Close area", exact: true }).count(), 0);
  await page.getByRole("button", { name: "Close Notes", exact: true }).click();
  await page.getByRole("button", { name: "Close Chat", exact: true }).click();
  await page.getByText("Drop a window here", { exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Close area", exact: true }).count(), 0, "the final empty area stays available");
  assert.equal(await page.getByRole("button", { name: "Maximize area", exact: true }).count(), 0);
  await view("Chat").click();
  assert.equal(await page.getByRole("textbox", { name: "Chat draft" }).evaluate((element, original) => element === original, chat), true);
  await startDrag(tab("Chat"), groups.first());
  await dropGuide("group-left");
  assert.equal(await groups.count(), 2);
  await screenshot("tab-split-left");
  await page.getByText("Drop a window here", { exact: true }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Close area", exact: true }).count(), 1, "only the redundant empty area has an area close button");
  assert.equal(await page.getByRole("button", { name: "Maximize area", exact: true }).count(), 1);
  await page.reload();
  await page.getByText("Drop a window here", { exact: true }).waitFor();
  assert.equal(await groups.count(), 2, "the split and closed apps survive reload");
  assert.equal(await tab("Notes").count(), 0);
  await page.evaluate(() => window.dockingFixture.setApps(["notes", "board"]));
  await tab("Board").waitFor();
  assert.equal(await tab("Chat").getAttribute("aria-selected"), "true");
  await page.evaluate(() => window.dockingFixture.setApps([]));
  await tab("Board").waitFor({ state: "hidden" });
  await page.evaluate(() => window.dockingFixture.setRun("second"));
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  await page.evaluate(() => window.dockingFixture.setRun("first"));
  await page.waitForFunction(() => document.querySelectorAll("[data-dock-group]").length === 1);
  await page.getByRole("button", { name: "Reset layout", exact: true }).click();
  assert.equal(await groups.count(), 1);
  await page.evaluate(() => document.documentElement.setAttribute("data-theme", "dark"));
  assert.equal(await tab("Chat").isVisible(), true);
  await rail.getByRole("button", { name: "Files", exact: true }).click();
  await page.reload();
  await sidebar.waitFor();
  assert.equal(await sidebar.getAttribute("data-dock-sidebar"), "docked");
  assert.equal(await page.getByRole("button", { name: "Unpin sidebar", exact: true }).getAttribute("aria-pressed"), "true");
  await page.getByRole("button", { name: "Unpin sidebar", exact: true }).click();
  await page.mouse.move(10, 100);
  await page.waitForTimeout(400);
  assert.equal(await sidebar.isVisible(), false, "unpin hides the docked sidebar");
  await rail.getByRole("button", { name: "Files", exact: true }).hover();
  await sidebar.waitFor();
  assert.equal(await page.getByRole("button", { name: "Pin sidebar", exact: true }).getAttribute("aria-pressed"), "false");
  await page.getByRole("button", { name: "Pin sidebar", exact: true }).click();
  const grip = page.getByRole("separator", { name: "Resize sidebar" });
  await grip.focus();
  await page.keyboard.press("ArrowLeft");
  const saved = (await box(sidebar)).width;
  await page.reload();
  await sidebar.waitFor();
  assert.equal((await box(sidebar)).width, saved);
  assert.equal(await sidebar.getAttribute("data-dock-sidebar"), "docked");
  await rail.getByRole("button", { name: "Files", exact: true }).click();
  await sidebar.waitFor({ state: "hidden" });
  await page.mouse.move(10, 100);
  await rail.getByRole("button", { name: "Files", exact: true }).hover();
  await sidebar.waitFor();
  await page.getByRole("textbox", { name: "Files draft" }).click();
  await page.mouse.move(10, 100);
  await sidebar.waitFor({ state: "hidden" });
  await rail.getByRole("button", { name: "Files", exact: true }).hover();
  await sidebar.waitFor();
  const savedSides = await page.evaluate(() => Object.entries(localStorage)
    .filter(([key]) => key.startsWith("ragents.docking:"))
    .map(([, value]) => JSON.parse(value).side.mode));
  assert.ok(savedSides.length > 0);
  assert.ok(savedSides.every((mode) => mode !== "hover-preview"), "hover previews are never persisted");
  await page.mouse.move(10, 100);
  await page.reload();
  await tab("Chat").waitFor();
  assert.equal(await sidebar.count(), 0, "hover previews do not survive reload");
  assert.deepEqual(errors, []);
});
