import type { Static, TSchema } from 'typebox';
type RAgentsCapability31InputReference0 = ({ "children": [RAgentsCapability31InputReference0, RAgentsCapability31InputReference0, ...Array<unknown>]; "direction": ("horizontal") | ("vertical"); "weights": [number, number, ...Array<unknown>]; }) | ({ /** Actor tiles only: false hides the chat composer in the tile; default true. Does not change permissions or the inspector */ "chatInput"?: boolean; /** Actor @handle or activated mini-app app:@handle/view-key or app:program-name/view-key; the server resolves the view ID */ "entity": string; });
export interface CapabilityContracts { "action_propose": { input: { "description"?: string; "input"?: { "label": string; "placeholder"?: string; "required": boolean; }; "parameters"?: Array<({ "name": string; "value": string; }) & ({ [key: string]: unknown })>; "title": string; }; output: Array<{ "payload": { /** ID of the proposed action */ "actionId": string; }; "type": "action.proposed"; }> };
"actor_input": { input: { /** Actor ID or handle */ "actor": string; "artifactIds"?: Array<string>; "content": string; }; output: Array<{ "payload": { /** ID of the receiving actor */ "actorId": string; /** ID of the enqueued input */ "inputId": string; }; "type": "actor.input.enqueued"; }> };
"actor_list": { input: { /** Also list the tool names of each actor with a fixed selection. */ "toolNames"?: boolean; }; output: Array<{ "createdBy": (null) | (string); "description": (null) | (string); "displayName": string; "handle": string; "id": string; "kind": ("agent") | ("human") | ("script"); "lifecycle": string; /** Number of selected tools; 0 is a plain LLM, null an open, dynamically resolved toolset. */ "toolCount": (null) | (number); /** Only with toolNames: true, for a fixed selection. */ "toolNames"?: Array<string>; }> };
"actor_program_activate": { input: { "actor"?: string; "name": string; }; output: { "active": true; "actor": string; "name": string; "views": number; } };
"actor_program_controls": { input: { /** Optional control name from the catalog, without UI. prefix. Only valid when topic is controls or omitted. */ "component"?: string; /** Default controls: query component names or types. Guide: read the short package workflow without component. */ "topic"?: ("controls") | ("guide"); }; output: ({ "components": Array<string>; }) | ({ "files": { [key: string]: unknown }; }) | ({ "guide": string; }) };
"actor_program_create": { input: { "name": string; "template": ("blank") | ("chat") | ("controls") | ("headless-counter") | ("shared-list") | ("text-analysis"); }; output: { "directory": string; "files": Array<string>; "name": string; } };
"actor_program_diagnostics": { input: { "name"?: string; }; output: string };
"actor_program_ensure": { input: { "name": string; }; output: { "actorId": string; "handle": string; "status": ("activated") | ("active") | ("installed") | ("restarted"); } };
"actor_program_list": { input: { [key: string]: never }; output: Array<({ "actor": string; "functions": Array<string>; "name": string; "views": Array<({ "name": string; "title": string; "visible": boolean; }) & ({ [key: string]: unknown })>; }) & ({ [key: string]: unknown })> };
"actor_program_remove": { input: { "name": string; }; output: { "removed": string; } };
"actor_restart": { input: { /** Handle or ID */ "actorId": string; "reason": string; }; output: Array<({ "payload": { /** ID of the primary actor */ "actorId": string; }; "type": "run.primary-actor-selected"; }) | ({ "payload": { /** ID of the restarted actor */ "actorId": string; }; "type": "actor.restarted"; })> };
"actor_stop": { input: { /** Handle or ID */ "actorId": string; "reason": string; }; output: Array<({ "payload": { /** ID of the interrupted turn */ "turnId": string; }; "type": "turn.interrupted"; }) | ({ "payload": { /** ID of the removed subscription */ "subscriptionId": string; }; "type": "subscription.removed"; }) | ({ "payload": { /** ID of the stopped actor */ "actorId": string; }; "type": "actor.stopped"; })> };
"actor_transcript": { input: { /** Handle with or without @, or ID of an actor of this run */ "actor": string; /** Upper limit in characters, default 20000; the oldest lines are dropped first */ "maxChars"?: number; }; output: { "actorId": string; "handle": string; "lines": number; "text": string; "truncated": boolean; } };
"actor_view_set_visibility": { input: { /** package-name/view-key or @handle/view-key of an activated view, without the surface entity prefix app:. No generated IDs needed. */ "view": string; "visible": boolean; }; output: { "view": string; "visible": boolean; } };
"agent_spawn": { input: { /** Very short description of the task for the participants overview, a few words like "checks the rule on comments" */ "description"?: string; /** Display name; defaults to the handle */ "displayName"?: string; "driver"?: ("agent") | ("manual") | ("script"); /** Handle or ID of an LLM agent of this run whose model context up to the end of its last finished turn is copied into the new agent */ "forkOf"?: string; "handle": string; "isolateWorkspace"?: boolean; /** Model from model_list. Required for an LLM agent unless profile supplies a model; also overrides the profile's model. */ "model"?: string; /** Execution profile from model_list. Normally supply this field: an LLM agent needs a model-bearing profile or an explicit model. The caller's model is not inherited. */ "profile"?: string; "prompt": string; /** Provider from model_list for an explicit model selection; may be omitted when the profile or an unambiguous catalog entry supplies it. */ "provider"?: string; "thinking"?: ("high") | ("low") | ("max") | ("medium") | ("minimal") | ("off") | ("xhigh"); /** Required explicit selection: [] for plain text-only work including app-mediated conversations; an array for exact existing tool names; null only when the task needs an open, dynamically resolved toolset. Never inherits the caller's tools. Names of future, not yet activated actor functions are invalid; choose null when those must become available later. */ "tools": (Array<string>) | (null); "turnTimeoutMs"?: number; "withoutCapabilities"?: Array<("action.propose") | ("actor.input") | ("agent.spawn") | ("artifact.publish") | ("event.subscribe") | ("execution.stopOwned") | ("plugin.state.write") | ("run.configure") | ("script.start") | ("workspace.use")>; }; output: { /** Actual unique handle, including any suffix assigned during creation. */ "handle": string; /** Stable actor reference for actor_input and other functions. */ "id": string; } };
"artifact_publish": { input: { "content": string; "mediaType": string; "previousVersionId"?: string; "title": string; }; output: Array<{ "payload": { "artifact": { /** ID of the artifact; artifact_read reads it with this */ "id": string; }; }; "type": "artifact.published"; }> };
"artifact_read": { input: { "artifactId": string; }; output: { "artifact": { "createdAt": string; "createdBy": string; "id": string; "mediaType": string; "previousVersionId": (null) | (string); "size": number; "title": string; }; "content": string; "encoding": ("base64") | ("utf8"); } };
"ask_user": { input: ({ /** true = multiple choice allowed */ "multi"?: boolean; /** Answer options (2 to 6) */ "options": Array<string>; /** The question to the user, short and concrete */ "question": string; }) & ({ [key: string]: unknown }); output: string };
"bash": { input: ({ /** Bash command to execute */ "command": string; /** Folder to run the command in: relative to the working directory or starting with a workspace alias such as @name; defaults to the working directory */ "cwd"?: string; /** Timeout in seconds (default 120, maximum 3600) */ "timeout"?: number; }) & ({ [key: string]: unknown }); output: string };
"browser_check": { input: { /** Expected number of visible matches of target instead of exactly one; 0 asserts absence. Requires target without nth or first. */ "count"?: number; /** true (default): the check also fails on any browser error collected since the last navigation. false: ignore browser errors and judge only the assertions; use this when the page has known noise such as 404s or third-party script errors that are not part of the check. */ "noErrors"?: boolean; /** Use exactly one of role (with optional name), label, text, testId, css. Resolve semantic targets server-side; never copy snapshot element IDs. Ambiguous targets are errors naming the candidates unless nth or first selects one. */ "target"?: { /** CSS selector for elements without useful accessible names. */ "css"?: string; /** Use the first match when the target matches several elements; not together with nth. */ "first"?: boolean; /** CSS selector of an iframe containing the target. */ "frame"?: string; /** Exact form label. */ "label"?: string; /** Exact accessible name for role. */ "name"?: string; /** 0-based index among all matches when the target matches several elements; not together with first. */ "nth"?: number; /** Accessible role, e.g. button, textbox, link, combobox. */ "role"?: string; /** data-testid value. */ "testId"?: string; /** Exact visible text. */ "text"?: string; }; "text"?: string; "url"?: string; }; output: { "assertions": Array<string>; "checkedAt": string; "url": string; } };
"browser_click": { input: { /** Use exactly one of role (with optional name), label, text, testId, css. Resolve semantic targets server-side; never copy snapshot element IDs. Ambiguous targets are errors naming the candidates unless nth or first selects one. */ "target": { /** CSS selector for elements without useful accessible names. */ "css"?: string; /** Use the first match when the target matches several elements; not together with nth. */ "first"?: boolean; /** CSS selector of an iframe containing the target. */ "frame"?: string; /** Exact form label. */ "label"?: string; /** Exact accessible name for role. */ "name"?: string; /** 0-based index among all matches when the target matches several elements; not together with first. */ "nth"?: number; /** Accessible role, e.g. button, textbox, link, combobox. */ "role"?: string; /** data-testid value. */ "testId"?: string; /** Exact visible text. */ "text"?: string; }; }; output: { "errors": Array<string>; "snapshot": string; "title": string; "truncated": boolean; "url": string; } };
"browser_close": { input: { [key: string]: never }; output: { "closed": boolean; } };
"browser_fill": { input: { /** Use exactly one of role (with optional name), label, text, testId, css. Resolve semantic targets server-side; never copy snapshot element IDs. Ambiguous targets are errors naming the candidates unless nth or first selects one. */ "target": { /** CSS selector for elements without useful accessible names. */ "css"?: string; /** Use the first match when the target matches several elements; not together with nth. */ "first"?: boolean; /** CSS selector of an iframe containing the target. */ "frame"?: string; /** Exact form label. */ "label"?: string; /** Exact accessible name for role. */ "name"?: string; /** 0-based index among all matches when the target matches several elements; not together with first. */ "nth"?: number; /** Accessible role, e.g. button, textbox, link, combobox. */ "role"?: string; /** data-testid value. */ "testId"?: string; /** Exact visible text. */ "text"?: string; }; "value": string; }; output: { "errors": Array<string>; "snapshot": string; "title": string; "truncated": boolean; "url": string; } };
"browser_open": { input: { "url": string; }; output: { "errors": Array<string>; "snapshot": string; "title": string; "truncated": boolean; "url": string; } };
"browser_press": { input: { "key": string; /** Use exactly one of role (with optional name), label, text, testId, css. Resolve semantic targets server-side; never copy snapshot element IDs. Ambiguous targets are errors naming the candidates unless nth or first selects one. */ "target": { /** CSS selector for elements without useful accessible names. */ "css"?: string; /** Use the first match when the target matches several elements; not together with nth. */ "first"?: boolean; /** CSS selector of an iframe containing the target. */ "frame"?: string; /** Exact form label. */ "label"?: string; /** Exact accessible name for role. */ "name"?: string; /** 0-based index among all matches when the target matches several elements; not together with first. */ "nth"?: number; /** Accessible role, e.g. button, textbox, link, combobox. */ "role"?: string; /** data-testid value. */ "testId"?: string; /** Exact visible text. */ "text"?: string; }; }; output: { "errors": Array<string>; "snapshot": string; "title": string; "truncated": boolean; "url": string; } };
"browser_screenshot": { input: { "fullPage"?: boolean; "label"?: string; }; output: { "capturedAt": string; "markdown": string; "name": string; "path": string; "url": string; } };
"browser_select": { input: { "label": string; /** Use exactly one of role (with optional name), label, text, testId, css. Resolve semantic targets server-side; never copy snapshot element IDs. Ambiguous targets are errors naming the candidates unless nth or first selects one. */ "target": { /** CSS selector for elements without useful accessible names. */ "css"?: string; /** Use the first match when the target matches several elements; not together with nth. */ "first"?: boolean; /** CSS selector of an iframe containing the target. */ "frame"?: string; /** Exact form label. */ "label"?: string; /** Exact accessible name for role. */ "name"?: string; /** 0-based index among all matches when the target matches several elements; not together with first. */ "nth"?: number; /** Accessible role, e.g. button, textbox, link, combobox. */ "role"?: string; /** data-testid value. */ "testId"?: string; /** Exact visible text. */ "text"?: string; }; }; output: { "errors": Array<string>; "snapshot": string; "title": string; "truncated": boolean; "url": string; } };
"browser_snapshot": { input: { [key: string]: never }; output: { "errors": Array<string>; "snapshot": string; "title": string; "truncated": boolean; "url": string; } };
"browser_view_screenshot": { input: { [key: string]: never }; output: string };
"browser_viewport": { input: { "height": number; "width": number; }; output: { "errors": Array<string>; "snapshot": string; "title": string; "truncated": boolean; "url": string; } };
"canvas_layout_place": { input: { /** horizontal: to the right of the current layout (default); vertical: below it */ "direction"?: ("horizontal") | ("vertical"); /** Actor @handle or activated mini-app app:@handle/view-key or app:program-name/view-key */ "entity": string; /** Share of the placed tile against the existing arrangement's weight 1; default 1 */ "weight"?: number; }; output: { "placed": boolean; } };
"canvas_layout_replace": { input: ({ /** The whole arrangement: a tile or a binary split. Maximum 64 unique tiles and 16 nested splits. null clears the surface */ "root": (RAgentsCapability31InputReference0) | (null); }) & ({ [key: string]: unknown }); output: null };
"document_write": { input: { /** The complete content of the file */ "content": string; /** Path in the file store, e.g. topic/report.md */ "path": string; }; output: string };
"edit": { input: ({ /** One or more targeted replacements. Each edit is matched against the original file, not incrementally. Do not include overlapping or nested edits. If two changes touch the same block or nearby lines, merge them into one edit instead. */ "edits": Array<({ /** 1-based line number near the intended occurrence. The occurrence closest to it wins; a tie is an error. */ "nearLine"?: number; /** Replacement text for this targeted edit. */ "newText": string; /** 1-based index of the occurrence to replace when oldText is not unique. A failed edit lists all occurrences with their line numbers, so pick the index from that list. */ "occurrence"?: number; /** Exact text for one targeted replacement. It must be unique in the original file unless occurrence, nearLine or replaceAll is set, and must not overlap with any other edits[].oldText in the same call. */ "oldText": string; /** Replace every occurrence of oldText. Cannot be combined with occurrence or nearLine, and must not be used to change only some of them. */ "replaceAll"?: boolean; }) & ({ [key: string]: unknown })>; /** Path to the file to edit (relative or absolute) */ "path": string; }) & ({ [key: string]: unknown }); output: string };
"event_query": { input: { "actorIds"?: Array<string>; "eventIds"?: Array<string>; /** Every journal event type can be queried. Only the observable types can be subscribed to; event_subscribe shows them. */ "eventTypes"?: Array<string>; "limit"?: number; }; output: Array<{ "actorId": string; "causationId": (null) | (string); "commandId": string; "correlationId": (null) | (string); "eventId": string; "occurredAt": string; "payload": unknown; "runId": string; "schemaVersion": 3; "sequence": number; "type": string; }> };
"event_subscribe": { input: { "eventTypes": Array<("action.proposed") | ("action.resolved") | ("actor.restarted") | ("actor.stopped") | ("artifact.published") | ("model.output.completed") | ("model.reasoning.completed") | ("runtime.output.recorded") | ("tool.call.completed") | ("tool.call.failed") | ("tool.call.started") | ("turn.finished") | ("turn.interrupted")>; "includeSelf"?: boolean; "sourceActorIds"?: Array<string>; "sourceActorKinds"?: Array<("agent") | ("human") | ("script")>; }; output: { /** The resolved source actors as @handle where resolvable, otherwise as ID; null = all. */ "sources": (Array<string>) | (null); /** ID of the subscription; event_unsubscribe takes it as subscriptionId */ "subscriptionId": string; } };
"event_subscription_list": { input: { [key: string]: never }; output: Array<({ "createdAt": string; "createdBy": string; "createdSequence": number; "endedAt": string; "eventTypes": Array<string>; "includeSelf": boolean; "reason": string; /** Source actors as ID; null = all. ID and @handle are equivalent as input. */ "sourceActorIds": (Array<string>) | (null); "sourceActorKinds": (Array<("agent") | ("human") | ("script")>) | (null); "sourceEventId": string; /** The same sources as @handle where resolvable; otherwise the ID. */ "sources": (Array<string>) | (null); "status": "failed"; "subscriberId": string; /** ID of the subscription; event_unsubscribe takes it as subscriptionId */ "subscriptionId": string; }) | ({ "createdAt": string; "createdBy": string; "createdSequence": number; "endedAt": string; "eventTypes": Array<string>; "includeSelf": boolean; "reason": string; /** Source actors as ID; null = all. ID and @handle are equivalent as input. */ "sourceActorIds": (Array<string>) | (null); "sourceActorKinds": (Array<("agent") | ("human") | ("script")>) | (null); /** The same sources as @handle where resolvable; otherwise the ID. */ "sources": (Array<string>) | (null); "status": "removed"; "subscriberId": string; /** ID of the subscription; event_unsubscribe takes it as subscriptionId */ "subscriptionId": string; }) | ({ "createdAt": string; "createdBy": string; "createdSequence": number; "eventTypes": Array<string>; "includeSelf": boolean; /** Source actors as ID; null = all. ID and @handle are equivalent as input. */ "sourceActorIds": (Array<string>) | (null); "sourceActorKinds": (Array<("agent") | ("human") | ("script")>) | (null); /** The same sources as @handle where resolvable; otherwise the ID. */ "sources": (Array<string>) | (null); "status": "active"; "subscriberId": string; /** ID of the subscription; event_unsubscribe takes it as subscriptionId */ "subscriptionId": string; })> };
"event_unsubscribe": { input: { "reason": string; /** subscriptionId from event_subscribe or event_subscription_list */ "subscriptionId": string; }; output: null };
"fsharp_close": { input: ({ /** The open root to stop; omit for every instance of this run */ "root"?: string; }) & ({ [key: string]: unknown }); output: string };
"fsharp_diagnostics": { input: ({ /** Files relative to the workspace root; omit for all changed files */ "paths"?: Array<string>; /** Ask only the instance of this open root */ "root"?: string; /** Also list warnings (default: only counted) */ "warnings"?: boolean; }) & ({ [key: string]: unknown }); output: string };
"fsharp_open": { input: ({ /** the .sln file (or a single .fsproj), relative to the workspace root */ "root": string; }) & ({ [key: string]: unknown }); output: string };
"model_list": { input: { "driver"?: ("agent") | ("manual") | ("script"); }; output: { "models": Array<{ "driver": string; "label": string; "model": string; "provider": string; /** Thinking levels that agent_spawn accepts for this model. */ "thinking": Array<string>; }>; "profiles": Array<({ "description": string; "driver": "agent"; "isolateWorkspace": boolean; "model": string; "name": string; "provider": string; "thinking"?: string; "turnTimeoutMs": (null) | (number); }) | ({ "description": string; "driver": ("manual") | ("script"); "isolateWorkspace": boolean; "name": string; "turnTimeoutMs": (null) | (number); })>; } };
"quick_answer": { input: ({ /** Repeat the current user question briefly in your own words. */ "question": string; /** A short sentence with the result of your normal chat answer. */ "text": string; }) & ({ [key: string]: unknown }); output: ({ "ok": true; }) & ({ [key: string]: unknown }) };
"read": { input: ({ /** Maximum number of lines to read */ "limit"?: number; /** Line number to start reading from (1-indexed) */ "offset"?: number; /** Path to the file to read (relative or absolute) */ "path": string; }) & ({ [key: string]: unknown }); output: string };
"roslyn_close": { input: ({ /** The open root to stop; omit for every instance of this run */ "root"?: string; }) & ({ [key: string]: unknown }); output: string };
"roslyn_diagnostics": { input: ({ /** Files relative to the workspace root; omit for all changed files */ "paths"?: Array<string>; /** Ask only the instance of this open root */ "root"?: string; /** Also list warnings (default: only counted) */ "warnings"?: boolean; }) & ({ [key: string]: unknown }); output: string };
"roslyn_open": { input: ({ /** the .sln file (or a single .csproj), relative to the workspace root */ "root": string; }) & ({ [key: string]: unknown }); output: string };
"roslyn_solutions": { input: { [key: string]: unknown }; output: string };
"run_configure": { input: { /** Handle or ID of the actor the user's chat talks to */ "primaryActor"?: string; /** New title of the run */ "title"?: string; }; output: null };
"run_script_list": { input: { [key: string]: never }; output: Array<{ "available": boolean; "description": string; "entry": string; "reason"?: string; "title": string; }> };
"run_script_start": { input: { /** The entry from run_script_list */ "entry": string; /** Start value of the script; omit it for none */ "input"?: unknown; }; output: { "count": number; "handle": string; } };
"run_stop": { input: { [key: string]: never }; output: { "requested": true; } };
"show_document": { input: { /** The complete content - for files from the working directory and for self-produced content, i.e. everything that is not in the file store. content and path exclude each other: valid are { title, content, format } for self-produced content and files of the working directory, and { title, path, format } for files of the file store - exactly one of the two must be set. */ "content"?: string; /** Rendering, default markdown */ "format"?: ("html") | ("markdown") | ("text"); /** File from this run's file store, relative to the store (e.g. topic/file.md). Only files stored there can be shown this way - for paths of the working directory use content. The content is shown directly from the file and never has to be retyped. content and path exclude each other: valid are { title, content, format } for self-produced content and files of the working directory, and { title, path, format } for files of the file store - exactly one of the two must be set. */ "path"?: string; /** Title of the display, e.g. the file name */ "title": string; }; output: string };
"todo_replace": { input: ({ "todos": Array<({ "id": string; /** open = not started, active = in progress, completed = done; pending, in_progress and done are accepted as well */ "status": ("active") | ("completed") | ("done") | ("in_progress") | ("open") | ("pending"); "text": string; }) & ({ [key: string]: unknown })>; }) & ({ [key: string]: unknown }); output: null };
"typescript_close": { input: ({ /** The open root to stop; omit for every instance of this run */ "root"?: string; }) & ({ [key: string]: unknown }); output: string };
"typescript_diagnostics": { input: ({ /** Files relative to the workspace root; omit for all changed files */ "paths"?: Array<string>; /** Ask only the instance of this open root */ "root"?: string; /** Also list warnings (default: only counted) */ "warnings"?: boolean; }) & ({ [key: string]: unknown }); output: string };
"typescript_open": { input: ({ /** the directory whose tsconfig.json projects should be served (e.g. src), relative to the workspace root */ "root": string; }) & ({ [key: string]: unknown }); output: string };
"watch_create": { input: { /** Wake condition as a TypeScript function body of (now: WatchState, before: WatchState) => string | undefined; returns the wake reason as text or undefined. WatchState: source { lifecycle idle|running|stopped, completedTurns, lastTurn { status, reason? }, pendingInputs, pendingActions, lastOutput? }, observed (result of the observe operation as Record<string, unknown>), stalledForSeconds (only when stalled). before is the state at the last wake. Example: return now.source.completedTurns > before.source.completedTurns && now.observed?.phase !== "ready" ? "Turn ended, task not finished" : undefined; */ "condition": string; /** Text appended to every wake, e.g. how the woken actor should react */ "instruction"?: string; /** Named operation without input whose result extends the observed state and is compared by difference */ "observe"?: string; /** Observed actor as @handle or id */ "source": string; /** Seconds without an event of the observed actor after which the state reports stalledForSeconds */ "stallAfterSeconds"?: number; /** Actor to wake as @handle or id; if omitted, the caller */ "target"?: string; }; output: { /** Wake condition as a TypeScript function body */ "condition": string; /** Id of the watch for watch_remove */ "id": string; /** Time of the last evaluation */ "lastEvaluatedAt"?: string; "lastVerdict"?: { /** Time of the evaluation */ "at": string; /** Changes since the last wake that the evaluation saw */ "changes": Array<string>; /** Reason the condition returned, or 'Condition not met' */ "reason": string; /** Whether the watch woke */ "wake": boolean; }; /** Named operation whose result belongs to the observed state */ "observe"?: string; /** Observed actor as @handle */ "source": string; /** Seconds without an event of the observed actor after which the state reports a stall */ "stallAfterSeconds"?: number; /** Woken actor as @handle */ "target": string; /** Number of wakes so far */ "wakes": number; } };
"watch_list": { input: { [key: string]: never }; output: Array<{ /** Wake condition as a TypeScript function body */ "condition": string; /** Id of the watch for watch_remove */ "id": string; /** Time of the last evaluation */ "lastEvaluatedAt"?: string; "lastVerdict"?: { /** Time of the evaluation */ "at": string; /** Changes since the last wake that the evaluation saw */ "changes": Array<string>; /** Reason the condition returned, or 'Condition not met' */ "reason": string; /** Whether the watch woke */ "wake": boolean; }; /** Named operation whose result belongs to the observed state */ "observe"?: string; /** Observed actor as @handle */ "source": string; /** Seconds without an event of the observed actor after which the state reports a stall */ "stallAfterSeconds"?: number; /** Woken actor as @handle */ "target": string; /** Number of wakes so far */ "wakes": number; }> };
"watch_remove": { input: { /** Id from watch_create or watch_list */ "id": string; /** Reason for the removal */ "reason": string; }; output: { "removed": true; } };
"write": { input: ({ /** Content to write to the file */ "content": string; /** Path to the file to write (relative or absolute) */ "path": string; }) & ({ [key: string]: unknown }); output: string }; }
export interface RunContext<State> {
  readonly run: { readonly id: string };
  readonly actor: {readonly id: string; readonly handle: string};
  readonly std: RAgentsStd;
  readonly invocation: { readonly id: string; readonly kind: string };
  readonly principal: { readonly id: string; readonly kind: string };
  readonly signal: AbortSignal;
  readonly state: { read(): Readonly<State>; replace(value: State): void };
  readonly functions: {readonly [Name in keyof CapabilityContracts]: (...args: {} extends CapabilityContracts[Name]['input'] ? [input?: CapabilityContracts[Name]['input']] : [input: CapabilityContracts[Name]['input']]) => Promise<CapabilityContracts[Name]['output']>};
  log(value: unknown): void;
  throwIfAborted(): void;
  /** Ends a start of this run script with a JSON result; the host delivers it once to whoever started it. Only in onStart, onInput and onResult; outside onStart, name the start. */
  finish(result: unknown, options?: { readonly summary?: string; readonly start?: number }): void;
}

interface RAgentsMediatorEntry {
  readonly from: string | null;
  readonly text: string;
}

interface RAgentsMediatorState {
  readonly entries: ReadonlyArray<RAgentsMediatorEntry>;
  readonly done: boolean;
}

/** Every target is an actor id, a handle or @handle and must be a key of the table. */
type RAgentsMediatorTargets =
  | ReadonlyArray<string>
  | ((entry: RAgentsMediatorEntry) => string | ReadonlyArray<string> | null)
  | null;

interface RAgentsMediatorConfig {
  /** Every key is an actor id, a handle or @handle; handles are matched case-insensitively. */
  readonly table: Readonly<Record<string, RAgentsMediatorTargets>>;
  /** to is an actor id, a handle or @handle and must be a key of the table. */
  readonly start: { readonly to: string; readonly text: string };
  readonly label: "handle" | "none";
  readonly maxEntries: number;
  readonly onEntry?: (entry: RAgentsMediatorEntry) => void | Promise<void>;
  readonly onRoute?: (entry: RAgentsMediatorEntry, target: string) => void | Promise<void>;
  readonly onDone: (entries: ReadonlyArray<RAgentsMediatorEntry>) => void | Promise<void>;
}

interface RAgentsMediators {
  route(config: RAgentsMediatorConfig): (input: unknown) => Promise<void>;
}

interface RAgentsStd {
  now(): string;
  id(): string;
  readonly mediators: RAgentsMediators;
}


export interface ActorInput {
  readonly id: string; readonly content: string; readonly artifactIds: readonly string[];
  readonly sourceEventIds: readonly string[]; readonly subscriptionId: string | null;
  readonly event: { readonly type: string; readonly eventId: string; readonly sequence: number; readonly occurredAt: string;
    readonly sourceActorId: string | null; readonly sourceActorHandle: string | null; readonly payload: {readonly text?:string; readonly [key:string]:unknown} } | null;
}
export interface ActorStart {
  readonly input: unknown; readonly options: Readonly<Record<string, unknown>>;
  readonly embedded: boolean; readonly startedBy: string; readonly count: number;
}
export interface ActorResult { readonly handle: string; readonly count: number; readonly result: unknown; readonly summary?: string }
export interface ActorFunction { label: string; description?: string; input: TSchema; output: TSchema; capabilities?: readonly string[]; confirmation?: string; tool?: { name: string; targets?: readonly string[]; card?: boolean } }
export interface ActorContract { state: TSchema; functions: Readonly<Record<string, ActorFunction>>; input?: {capabilities?: readonly string[]} }
export type ActorFunctions<C extends ActorContract> = { [K in keyof C['functions']]: (input: Static<C['functions'][K]['input']>, context: RunContext<Static<C['state']>>) => Static<C['functions'][K]['output']> | Promise<Static<C['functions'][K]['output']>> };
export type ActorImplementation<C extends ActorContract> = {functions: ActorFunctions<C>} & (C extends {input: unknown} ? {onInput: (input: ActorInput, context: RunContext<Static<C['state']>>) => void | Promise<void>; onStart?: (start: ActorStart, context: RunContext<Static<C['state']>>) => void | Promise<void>; onResult?: (result: ActorResult, context: RunContext<Static<C['state']>>) => void | Promise<void>} : {onInput?: never; onStart?: never; onResult?: never});
export declare function defineActor<const C extends ActorContract>(contract: C, implementation: ActorImplementation<C>): {contract:C} & ActorImplementation<C>;
