import { Type } from "typebox";
import { defineRunFunction, defineToolAvailability, holdsUsable, type RunFunction, type ToolContributor } from "@ragents/engine";
import { toolDescriptorFrom } from "@ragents/host/plugin-support/agent-tool.js";
import type { ActorProgramRuntime } from "./runtime.js";
import type { createProjectDiagnostics } from "./project-diagnostics.js";
const metadata = [
    { name: "actor_program_create", label: "Create Actor Program", description: "Create a private TypeScript package with fixed libraries.", longDescription: "Edit files in the returned directory using workspace tools: @actors/name, in a room @actors/room.name. The package belongs to your room." },
    { name: "actor_program_activate", label: "Activate Actor Program", description: "Typecheck, build and test a package, then activate its functions and optional views.", longDescription: "actor self or @handle attaches to an existing actor; omitted creates a TypeScript actor for a backend, or attaches static views to self." },
    { name: "actor_program_list", label: "List Actor Programs", description: "List active actor packages, functions and views.", longDescription: "A visible view is already open as a tab for the user. A view's ref is the package-name/view-key reference that view functions accept." },
    { name: "actor_program_remove", label: "Remove Actor Program", description: "Detach functions and views and stop the backend.", longDescription: "A TypeScript actor is stopped; an LLM actor retains its agent behavior." },
    { name: "actor_view_set_visibility", label: "Show or hide Actor View", description: "Set surface visibility by package-name/view-key or @handle/view-key.", longDescription: "Use names you chose; the server resolves the view ID. A unique view title also works." },
    { name: "actor_program_diagnostics", label: "Actor Program Diagnostics", description: "Read the last project diagnostics.", longDescription: "Changed errors are automatically supplied before the next model request." },
    { name: "actor_program_ensure", label: "Ensure Actor Program", description: "Make a package active once: return it when active, restart its stopped actor, activate it when installed, or install a shared package of the profile.", longDescription: "Safe to call on every start: an active package is returned unchanged and not rebuilt. status names what happened. actor_program_activate instead rebuilds and reactivates." },
] as const;
export const actorProgramManagementToolNames = metadata.map((entry) => entry.name);
export const actorProgramToolsAvailable = defineToolAvailability({ availability: "conditional", availabilityDetail: "For executable actors with agent.spawn and plugin.state.write." }, actor => actor.kind !== "human" && holdsUsable(actor, "agent.spawn") && holdsUsable(actor, "plugin.state.write"));
const name = (description: string) => Type.String({ pattern: "^[a-z][a-z0-9-]{0,63}$", description });
const packageName = (description: string) => Type.String({ pattern: "^(?:[a-z][a-z0-9-]{0,63}\\.)?[a-z][a-z0-9-]{0,63}$", description: `${description}; a bare name means your room's package, otherwise the main room's, room.name another room's` });
type Diagnostics = Pick<ReturnType<typeof createProjectDiagnostics>, "latest">;
const managementTools = (runtime: ActorProgramRuntime, diagnostics: Diagnostics): RunFunction[] => [
    defineRunFunction({ ...metadata[0], schema: Type.Object({ name: name("Name of the new package in your room: lowercase letters, digits and hyphens; its files go to the returned directory"), template: Type.Union(runtime.templates().map((entry) => Type.Literal(entry.id, { description: entry.description })), { description: "Template for the first files" }) }, { additionalProperties: false }), resultSchema: Type.Object({ name: Type.String(), directory: Type.String({ description: "Package folder for the file tools and as bash cwd" }), files: Type.Array(Type.String(), { description: "Created files relative to the package folder" }) }, { additionalProperties: false }), available: actorProgramToolsAvailable, executionMode: "sequential", run: (scope, _id, input) => runtime.scaffold(scope.caller.runId, scope.caller.actorId, input.name, input.template) }),
    defineRunFunction({ ...metadata[1], schema: Type.Object({ name: packageName("Package under @actors/ to check, build, test and activate"), actor: Type.Optional(Type.String({ description: "self or @handle of an existing actor that takes the package; an activated package keeps its actor" })) }, { additionalProperties: false }), resultSchema: Type.Object({ name: Type.String(), actor: Type.String({ description: "@handle of the actor that holds the package" }), views: Type.Number({ description: "Number of activated views" }), active: Type.Literal(true) }, { additionalProperties: false }), available: actorProgramToolsAvailable, executionMode: "sequential", run: (scope, id, input) => runtime.activate(scope.context(id), scope.caller.runId, input.name, scope.signal, input.actor) }),
    defineRunFunction({ ...metadata[2], schema: Type.Object({}, { additionalProperties: false }), resultSchema: Type.Array(Type.Object({ name: Type.String(), actor: Type.String(), functions: Type.Array(Type.String()), views: Type.Array(Type.Object({ name: Type.String(), ref: Type.String(), title: Type.String(), visible: Type.Boolean() })) })), available: actorProgramToolsAvailable, executionMode: "sequential", run: (scope) => runtime.list(scope.caller.runId, scope.caller.actorId) }),
    defineRunFunction({ ...metadata[3], schema: Type.Object({ name: packageName("Name of the active package") }, { additionalProperties: false }), resultSchema: Type.Object({ removed: Type.String() }, { additionalProperties: false }), available: actorProgramToolsAvailable, executionMode: "sequential", run: (scope, id, input) => runtime.remove(scope.context(id), scope.caller.runId, input.name) }),
    defineRunFunction({ ...metadata[4], schema: Type.Object({ view: Type.String({ minLength: 1, description: "package-name/view-key or @handle/view-key of an activated view, without the surface entity prefix app:. No generated IDs needed." }), visible: Type.Boolean({ description: "true shows the view as a tab for the user, false hides it" }) }, { additionalProperties: false }), resultSchema: Type.Object({ view: Type.String(), visible: Type.Boolean() }, { additionalProperties: false }), available: actorProgramToolsAvailable, executionMode: "sequential", run: (scope, id, input) => runtime.setVisibility(scope.context(id), scope.caller.runId, input.view, input.visible) }),
    defineRunFunction({ ...metadata[5], schema: Type.Object({ name: Type.Optional(packageName("Only this package; omitted, every package checked for this actor")) }, { additionalProperties: false }), resultSchema: Type.String(), available: actorProgramToolsAvailable, executionMode: "sequential", run: async (scope, _id, input) => diagnostics.latest(scope.caller.runId, scope.caller.actorId, input.name === undefined ? undefined : await runtime.packageKey(scope.caller.runId, scope.caller.actorId, input.name)) }),
    defineRunFunction({ ...metadata[6], schema: Type.Object({ name: packageName("Package of this run or a shared actor package of the profile, which lives in the main room") }, { additionalProperties: false }), resultSchema: Type.Object({ actorId: Type.String(), handle: Type.String(), status: Type.Union([Type.Literal("active"), Type.Literal("restarted"), Type.Literal("activated"), Type.Literal("installed")], { description: "active: already active, unchanged; restarted: its stopped actor was restarted; activated: built and activated from this run's package folder; installed: the shared package was installed" }) }, { additionalProperties: false }), available: actorProgramToolsAvailable, executionMode: "sequential", run: (scope, id, input) => runtime.ensure(scope.context(id), scope.caller.runId, input.name, scope.signal) }),
];
export const createActorProgramToolContributors = (runtime: ActorProgramRuntime, diagnostics: Diagnostics): readonly ToolContributor[] => [
    { name: "ragents.actor-programs.management", descriptors: metadata.map((item) => toolDescriptorFrom(item, actorProgramToolsAvailable)), tools: () => managementTools(runtime, diagnostics) },
    { name: "ragents.actor-programs.functions", descriptors: [], dynamic: true, tools: (context) => runtime.installedTools(context) },
];
